packages/spindle-ui/src/index.ts

`Icon`コンポーネント群を`export`するように修正しました。

chore: export icon components

---

packages/spindle-icons/CHANGELOG.md
packages/spindle-icons/package.json
packages/spindle-ui/CHANGELOG.md
packages/spindle-ui/package.json

- @openameba/spindle-icons@0.3.0
- @openameba/spindle-ui@0.2.0

chore(release): publish

---

.github/workflows/deploy-ui-catalog.yml

ついつい更新忘れちゃうので、mainブランチにSpindle UIの変更が入った時に自動でStorybookを更新するようにしてみました。手動タスクはまた必要になったら追加しようと思います〜

chore(spindle-ui): change trigger to deploy UI catalog

---

packages/spindle-ui/src/Button/Button.css

feat(spindle-ui): set line-height 1.3 in button

---

.github/workflows/release.yml

流れで`release`にしてしまいましたが、そんなコマンドはありましぇんでした:grimacing:

chore: fix lerna command to publish

---

package.json

速度改善を目的に、ESLintのcacheオプションを設定しました (いつものやつ)。
https://eslint.org/docs/user-guide/command-line-interface#options

chore: cache eslint result

---

.github/workflows/build-icon.yml

FIGMA tokenを設定するのをすっかり忘れておりました😩
Workflowでエラーが出ました。
https://github.com/openameba/spindle/runs/1361692062?check_suite_focus=true

chore: set Figma token

---

packages/spindle-ui/bundlesize.config.json
packages/spindle-ui/package.json
packages/spindle-ui/postcss.config.js
yarn.lock

TODOになっていた、CSSのminifyを適用し、ファイルバジェットも更新しました。
成果物を読むことはほぼなさそうなので、常にminifyしています。

Minify CSS by default

---

.github/workflows/release.yml

たびたび恐縮ですが、PRタイトルはハードコードでよかったので、変更しました。予期しない文字列が入ることも防ぎます。

chore: hard code PR title for releasing

---

README.md

READMEに各パッケージへのリンクを追加しました。こちらはテストに問題なければマージしてしまいます。

docs: add link to packages

---

packages/spindle-ui/src/IconButton/IconButton.css

`IconButton` の状態変化時のスタイルが一部抜けていたので、追加しました。

fix(spindle-ui): apply IconButton state styles

---

packages/spindle-ui/src/IconButton/IconButton.css
packages/spindle-ui/src/IconButton/IconButton.stories.mdx
packages/spindle-ui/src/IconButton/IconButton.tsx

IconButtonの `variant` のtypeに `lighted` 追加、`danger` のvariant追加

feat(spindle-ui): add lighetd, danger types to IconButton

---

.github/workflows/build-icon.yml
.github/workflows/build.yml
.github/workflows/deploy-ui-catalog.yml
.github/workflows/regression-test.yml
.github/workflows/release.yml
.github/workflows/test.yml
packages/spindle-icons/package.json

必要ない(今は使っていない) [prepareタスク](https://docs.npmjs.com/cli/v7/using-npm/scripts#life-cycle-scripts)により、`dist/` がpublish前にかならず空になっていたので、削除しアイコンファイルが配信されるようにしました🥲
<details>
<summary>spindle-icons % npm publish --dry-run</summary>
```
npm notice
npm notice 📦  @openameba/spindle-icons@0.9.0
npm notice === Tarball Contents ===
npm notice 20.3kB  LICENSE
npm notice 866B    package.json
npm notice 2.5kB   CHANGELOG.md
npm notice 5.2kB   README.md
npm notice 2.9kB   dist/pdf/755.pdf
npm notice 5.3kB   dist/pdf/abemakun.pdf
npm notice 4.0kB   dist/pdf/abematv.pdf
npm notice 2.7kB   dist/pdf/accesslink.pdf
npm notice 1.9kB   dist/pdf/accesspage_fill.pdf
npm notice 2.3kB   dist/pdf/accesspage.pdf
npm notice 2.2kB   dist/pdf/addressbook_fill.pdf
npm notice 2.7kB   dist/pdf/album_add_fill.pdf
npm notice …
```

fix(spindle-icons): remove unused npm task

---

packages/spindle-ui/README.md

docs(spindle-ui): update README for Spindle UI usage

---

packages/spindle-ui/src/Form/TextArea.css
packages/spindle-ui/src/Form/TextField.css

`<TextField />` と `<TextArea />` で `prefer-reduced-motion` を使うように修正しました。

Fix/fix to use prefers-reduced-motion in text field

---

.github/workflows/regression-test.yml

Regression testを勘でSpindle UIの変更があるときだけにしてみました。

chore: run regression test on Spindle UI update

---

packages/spindle-tokens/package.json

Spindle TokensのJSONが用意できてきたので、パッケージとして配信してみます。

chore(spindle-tokens): make public

---

CONTRIBUTING.md

docs: add guide for releasing packages

---

.github/workflows/build.yml
.github/workflows/test.yml
packages/spindle-ui/CHANGELOG.md
packages/spindle-ui/README.md
packages/spindle-ui/package.json
packages/spindle-ui/tsconfig.cjs.json
packages/spindle-ui/tsconfig.esm.json
packages/spindle-ui/tsconfig.json

利用箇所やファイルも増えてきたので、ESMを配信して読み込みの簡略化や、バンドルの軽量化をしてみようと思います。
`dist/esm/`などディレクトリを分けて配信するのが良さそうですが、現状[pathでインポートできるようにしている](https://github.com/openameba/spindle/pull/61)ので同階層に`mjs`ファイルを配置する方向で実装してみました。少しnpm scriptが複雑になっているのと、[利用側webpackの設定](https://github.com/webpack/webpack.js.org/blob/6d41707cd61bf3558cdaa3125b7c3226f8eebc99/src/content/configuration/module.mdx#resolvefullyspecified)が懸念ポイントではあります。
[仮配信して、実際に読み込んでみたサンプル](https://github.com/openameba/spindle/compare/chore/example-module?expand=1)ではうまく動いていそうな感じでした。
<details>
<summary>webpack-bundle-analyzer</summary>
```
cd examples/styled-components
npx webpack --profile --json > stats.json
npx webpack-bundle-analyzer stats.json
```
</details>
```
yarn add @openameba/spindle-ui@esm
```
※ 動作確認が終わり次第、latest配信します。 …

build(spindle-ui): esm

---

.github/workflows/regression-test.yml

reg-suitの出力に豆腐が含まれていたので修正を試みました。

ci: no tofu

---

packages/spindle-tokens/tokens/shadow/drop-shadow.json

Style Dictionaryでサイズとして認識したい項目にカテゴリを追加しました。
https://amzn.github.io/style-dictionary/#/transforms?id=sizepx
ref: #415 #416

feat(spindle-tokens): update design tokens

---

.github/workflows/visual-regression-test.yml

ci: improve VRT workflow

---

packages/spindle-hooks/CONTRIBUTING.md
packages/spindle-hooks/README.md
packages/spindle-hooks/docs/design-doc.md

Spindle Hooksのドキュメント周りを整備しました。
基本的にSpindle UIのドキュメントを参考にしています。
Spindle Hooksの方針として問題なさそうかなど確認お願いします

docs(spindle-hooks): add some docs

---

package.json
packages/spindle-hooks/.storybook/main.js
packages/spindle-hooks/jest.config.js
packages/spindle-hooks/package.json
packages/spindle-hooks/src/internal/useFlushSync/index.ts
packages/spindle-hooks/src/internal/useFlushSync/useFlushSync.ts
packages/spindle-hooks/src/useCarousel/useSliderTransition.ts
packages/spindle-hooks/src/useTimeDistance/useTimeDistance.test.ts
packages/spindle-hooks/src/useTimeDistance/useTimeDistance.ts
packages/spindle-hooks/tsconfig.json
packages/spindle-ui/package.json
packages/spindle-ui/tsconfig.json
yarn.lock

react18でおかしな挙動をすることがあるので修正しました
react18ではstate更新による再レンダリングが1つにまとめられますが、レンダリングの回数に意味を持つ場合、flushSyncを使うとレンダリングを分離できるのでこれを使うようにしました。

feat(spindle-hooks): support react18 for useCarousel

---

.renovaterc.json

chore: remove org name from renovate reviewers

---

packages/spindle-ui/.storybook/main.js
packages/spindle-ui/package.json
yarn.lock

storybookが正しく動いていなかったのでmdx-jsを1系を使うように修正しました

chore: use mdx-js/react@1.x

---

packages/spindle-ui/src/TextButton/TextButton.css
packages/spindle-ui/src/TextButton/TextButton.stories.mdx
packages/spindle-ui/src/TextButton/TextButton.test.tsx
packages/spindle-ui/src/TextButton/TextButton.tsx
packages/spindle-ui/src/TextButton/index.ts
packages/spindle-ui/src/index.css
packages/spindle-ui/src/index.ts

[TextLink](https://ameba-spindle.web.app/?path=/story/textlink--normal)のボタンバージョンを作成しました。button要素に変わった以外の振る舞いはTextLinkと同様です。

feat(spindle-ui): create TextButton

---

packages/spindle-hooks/src/internal/useFlushSync/useFlushSync.ts
packages/spindle-hooks/src/useCarousel/useAutoSlide.ts
packages/spindle-hooks/src/useCarousel/useCarousel.ts
packages/spindle-hooks/src/useCarousel/useSliderMoveEvent.ts
packages/spindle-ui/bundlesize.config.json
packages/spindle-ui/src/Dialog/Dialog.tsx
packages/spindle-ui/src/DropdownMenu/DropdownMenu.tsx
packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts
packages/spindle-ui/src/HeroCarousel/hooks/useAutoSlide.ts
packages/spindle-ui/src/HeroCarousel/hooks/useSliderMoveEvent.ts
packages/spindle-ui/src/Modal/AppealModal.tsx
packages/spindle-ui/src/SnackBar/SnackBar.tsx
packages/spindle-ui/src/StackNotificationManager/StackNotificationManager.stories.example.tsx
packages/spindle-ui/src/StackNotificationManager/hooks.ts
packages/spindle-ui/src/Toast/Toast.tsx

ESLintのWarningを修正（必要に応じてdisableコメントを追加）しました
主に https://github.com/openameba/spindle/pull/506 で追加した`eslint-plugin-react-hooks`に関するルールの問題修正です
- testが通ること（`lint:script`コマンドでESLintのWarningが発生しないこと）
- UIの挙動に変化がないこと

fix: warnings of ESLint rules

---

packages/spindle-theme-switch/README.md

docs(spindle-theme-switch): add demo

---

.github/workflows/build-icon-from-figma.yml
.github/workflows/build-icon.yml
.github/workflows/build-tokens.yml
.github/workflows/build.yml
.github/workflows/deploy-highlightjs-styles-preview.yml
.github/workflows/deploy-highlightjs-styles.yml
.github/workflows/deploy-hooks-catalog.yml
.github/workflows/deploy-hoooks-preview.yml
.github/workflows/deploy-theme-switch.yml
.github/workflows/deploy-ui-catalog.yml
.github/workflows/deploy-ui-preview.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/visual-regression-test.yml

CIのdeploy ui previewが落ちるようになってしまったため、Node.jsのversionをあげてみました

ci: upgrade node version

---

packages/spindle-ui/src/BottomButton/BottomButton.css
packages/spindle-ui/src/BottomButton/BottomButton.stories.mdx
packages/spindle-ui/src/BottomButton/BottomButton.tsx
packages/spindle-ui/src/BottomButton/index.ts
packages/spindle-ui/src/index.css

BottomButtonをSpindle UIに追加しました。
詳しい仕様はExperimental Features Docsを参照ください

feat(spindle-ui): create BottomButton

---

.github/workflows/release.yml

#554  で試してみたリリーススクリプトの改善ですが、ビルドの動作を見たく[bootstrapの方は変化させなくてよかった](https://github.com/openameba/spindle/actions/runs/3239256813)ので、戻しました。
lerna関連は #553 と一緒に調査してみます。

chore: bootstrap with npx

---

packages/spindle-syntax-themes/package.json
yarn.lock

Revert "chore(deps): update dependency puppeteer to v19"

---

.github/workflows/deploy-ui-catalog.yml

`lerna bootstrap --frozen-lockfile`はないと怒られるので使用しないようにしました
https://github.com/openameba/spindle/actions/runs/3407082492/jobs/5666359122

chore: use npx for bootstrap

---

packages/spindle-ui/src/Pagination/Pagination.stories.mdx

https://github.com/openameba/spindle/pull/599#issuecomment-1340306241
> 画面幅で表示が変わる4ケース + showTotal:true + onPageChange説明、合計6パターンで網羅できそう
を踏まえstorybookのパターンを修正してみました。
storybookでパターンが変更されているか確認いただければと。

fix(spindle-ui): pagination story

---

packages/spindle-ui/src/Pagination/Pagination.stories.mdx

Paginationのstory docs pageを修正しました。
前よりは見やすくなったかなーと思います。
- total部分を大見出しとして各currentはその子供としてグループ化
- 各パターンにuseShowItemでどの条件になるのかを記載
Source codeを複数（パターン分）記載しようかとも思ったのですがどうしてもできなくて一個にしています。
コード例としてはまぁ担保できているかな。という。
https://github.com/openameba/spindle/issues/605

docs(spindle-ui): update pagination

---

.textlintignore

https://github.com/openameba/spindle/pull/623#discussion_r1066756728 の通りです 🚀

chore: add spindle-ui/CHANGELOG to textlintignore

---

packages/spindle-tokens/tokens/animation/animation.json
packages/spindle-tokens/tokens/animation/duration.json
packages/spindle-tokens/tokens/animation/easing.json

アニメーション用のトークンができあがってきたので、Spindle Tokensに定義しておきます。トークンの構造は以下のとおりです。Spindle Tokensでは「Easing」「Duration」「Animation Type」まで定義し、「Animation Type」をSpindle UIを含む各UIコンポーネントで利用するイメージです。
各値についてはFigmaで確認いただければと思います。
- FigmaのStylesでの定義はアニメーションに対応していないのでFigmaデータを元に手動でJSON化しています
- 将来的に各プラットフォームで利用する想定で細分化して定義しています
- 固有名詞は大文字始まり、プロパティは小文字始まりで記述しています

feat(spindle-tokens): create animation tokens

---

packages/spindle-ui/src/Breadcrumb/Breadcrumb.css
packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx

https://github.com/openameba/spindle/pull/639#issue-1537567406 の内容で、コミットをまとめるために再度PR出しました！🙇‍♂️

fix(spindle-ui): remove underline when no href

---

packages/spindle-ui/src/Modal/SemiModal.css
packages/spindle-ui/src/Modal/SemiModal.stories.example.tsx
packages/spindle-ui/src/Modal/SemiModal.stories.mdx
packages/spindle-ui/src/Modal/SemiModal.tsx
packages/spindle-ui/src/Modal/index.css

ユーザーに画面を遷移させることなくモードを切り替えたいときに使用するSemiModalを作成しました。
- スタイルとロジックの大半はAppealModalと共通しています
Popup Modal - PC
https://user-images.githubusercontent.com/57176655/213113486-3efccc94-c743-4baf-a4d2-9e38677cca60.mov
Popup Modal - SP
https://user-images.githubusercontent.com/57176655/213113175-5122025e-1bec-4b52-b913-a3bfb84711fb.mov
Sheet Modal - PC
https://user-images.githubusercontent.com/57176655/213113339-1664d99e-e19a-4862-b83c-ff8603c6307f.mov
Sheet Modal - SP
https://user-images.githubusercontent.com/57176655/213112784-ddb5f7a2-c559-4243-adb1-76b61c83be44.mov

feat(spindle-ui): create SemiModal

---

CONTRIBUTING.md

docs: update release flow

---

packages/spindle-ui/src/TextButton/TextButton.stories.mdx
packages/spindle-ui/src/TextLink/TextLink.stories.mdx

TextLinkとTextButtonのドキュメントを眺めていたところ、軽微な修正点を見つけたので修正しました 🚀

docs(spindle-ui): fix docs for TextLink and TextButton

---

packages/spindle-ui/.scaffdog/component.md

scaffdogで生成したxxx.stories.mdxが動作しない不具合を修正しました。
closes: #733 
refs: #579

docs(spindle-ui): storybook scaffolding

---

packages/spindle-tokens/package.json

_乱視で複数見えていました :shushing_face:_

fix(spindle-tokens): chain commands

---

.github/workflows/visual-regression-test.yml

https://github.com/openameba/spindle/pull/322#issuecomment-1676515457 での一連の流れからVRTのワークフローの条件を変更しました。
`if:`に条件を全て記述すると読みづらく解読も大変なため、個々のステップでの`if:`で条件を判定するようにしました。
基本的に動作しないよう初期値をfalseにして、条件に当てはまったらtrueとして実行するようにしています。（ボットの判定だけは一連の条件に当てはまっていたとしてもfalseに戻し実行されないようにしています）

ci: update vrt execute condition

---

.github/workflows/deploy-highlightjs-styles-preview.yml
.github/workflows/deploy-highlightjs-styles.yml
.github/workflows/deploy-hooks-catalog.yml
.github/workflows/deploy-theme-switch.yml
.github/workflows/deploy-ui-catalog.yml

https://github.com/openameba/spindle/actions/runs/5947115208/job/16128708741 でエラーが出ていたので、liveチャンネルへのデプロイも公式actionを使うようにしました。
以下のactionで動作テストしました。
- spindle-hooks: https://github.com/openameba/spindle/actions/runs/5947818511/job/16130476101?pr=787
- spindle-syntax-themes: https://github.com/openameba/spindle/actions/runs/5947885928/job/16130651934?pr=787
- spindle-theme-switch: https://github.com/openameba/spindle/actions/runs/5947818505/job/16130475812?pr=787
- spindle-ui: https://github.com/openameba/spindle/actions/runs/5947818510/job/16130475905?pr=787

deploy firebase hosting with official action

---

.github/workflows/build-icon-from-figma.yml
.github/workflows/build-icon.yml
.github/workflows/build-tokens.yml

peter-evans/create-pull-requestでの人物関連をかっこよくしてみました。 (動くのか？)
ref: 
- https://github.com/openameba/ameba-color-palette.css/pull/93#discussion_r1267431718
- https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md#behaviour-changes-2

ci: set bot user as author

---

packages/spindle-ui/src/Dialog/Dialog.stories.mdx

fix: #780
全ての実装サンプルの一番始めのフォーカス可能な要素にautofocus属性を付与するようにしました。

docs(spindle-ui): implement autofocus for enhanced UI interaction

---

.github/workflows/release.yml

chore: update versioning commit message

---

.github/workflows/lint-commit-message.yml

ci: change to use sha from branch name

---

packages/spindle-ui/regconfig.json

VRTが動き出したところ
Ω「ｳｯ、さすがにdot多いな・・」
と感じたため、table形式に変更してみました。
https://github.com/reg-viz/reg-suit/blob/master/packages/reg-notify-github-plugin/README.md#configure

ci(spindle-ui): update reg-suit style to small table

---

packages/spindle-ui/src/ButtonGroup/ButtonGroup.css

fix: #809 
[最新のブラウザサポート](#876)に準じて記述しています。

fix(spindle-ui): margin in ButtonGroup

---

.github/workflows/dependabot-auto-approve.yml

コピペです
https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request

ci: auto approve dependabot

---

.github/workflows/build-icon-from-figma.yml
.github/workflows/build-icon.yml
.github/workflows/build-tokens.yml
.github/workflows/build.yml
.github/workflows/deploy-highlightjs-styles-preview.yml
.github/workflows/deploy-highlightjs-styles.yml
.github/workflows/deploy-hooks-catalog.yml
.github/workflows/deploy-hoooks-preview.yml
.github/workflows/deploy-theme-switch-preview.yml
.github/workflows/deploy-theme-switch.yml
.github/workflows/deploy-ui-catalog.yml
.github/workflows/deploy-ui-preview.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/visual-regression-test.yml

#1103 が済みましたので、CI上のnodeを20にしておきます。

ci: update node version to 20

---

.github/workflows/build-icon.yml
.github/workflows/figma-code-connect.yml
packages/spindle-ui/.npmignore
packages/spindle-ui/figma.config.json
packages/spindle-ui/package.json
packages/spindle-ui/scripts/figma-connect-icons.ts
packages/spindle-ui/src/Button/Button.figma.tsx
packages/spindle-ui/src/Dialog/Dialog.figma.tsx
packages/spindle-ui/src/Form/Checkbox.figma.tsx
packages/spindle-ui/src/Form/Radio.figma.tsx
packages/spindle-ui/src/Form/ToggleSwitch.figma.tsx
packages/spindle-ui/src/IconButton/IconButton.figma.tsx
packages/spindle-ui/src/InlineNotification/InlineNotification.figma.tsx
packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.figma.tsx
packages/spindle-ui/src/SegmentedControl/SegmentedControl.figma.tsx
packages/spindle-ui/src/SnackBar/SnackBar.figma.tsx
packages/spindle-ui/src/icons.figma.tsx
yarn.lock

[Figma Code Connect](https://help.figma.com/hc/en-us/articles/23920389749655-Code-Connect)の初期設定をしました。初期設定では、依存ライブラリのインストール、CI連動、接続できるコンポーネント対応をしました。
今後コンポーネント追加していく予定です。

Initial Setup for Figma Connect

---

bin/outputExtensionReplace.js

[Spindle Icon更新のActionがこけていた](https://github.com/openameba/spindle/actions/runs/13153707508/job/36705992371#step:6:2037)ので修正しました。
https://github.com/openameba/spindle/pull/1178 で追加されたファイルっぽいです。

style: tslintエラー修正

---

packages/spindle-hooks/package.json

chore: publish

---

.renovaterc.json

共通化したrenovateの設定を作ったので、できるだけそれを使うようにしました。

chore: renovate の設定を更新した

---

.npmrc
.renovaterc.json
.yarnrc

できるだけオートマージしたいかなーと
ただ、VRTでたびたびコケているような気はするのでCIの改善が必要かもしれない
- **chore: バージョン固定でインストールする**
- **chore: チェックが通るのならそのままマージする**

chore: update renovate configs

---

packages/spindle-mcp-server/README.md

docs(spindle-mcp-server): correct mcp name

---

.github/workflows/release.yml
package.json
yarn.lock

https://github.com/openameba/spindle/pull/1402#issuecomment-3326114670

ci: revert custom OIDC implementation in release workflow 

---

.claude/commands/create-issue.md
.cursor/commands/create-issue.md
AGENTS.md
CLAUDE.md

- Add create-issue command for both Claude and Cursor
- Update agent guidelines for issue creation workflow
- Enhance development workflow with Linear integration
---
This pull request introduces standardized procedures and documentation for creating issues using both Claude and Cursor agents. It adds detailed instructions and pre-flight checklists for issue creation, and updates the main agent documentation to reference these new guides.
Documentation and workflow improvements for issue creation:
* Added a comprehensive `create-issue` command guide for Claude, including requirements, tool setup, pre-flight checklist, and usage instructions in `.claude/commands/create-issue.md`
* Added a similar `create-issue` command guide for Cursor, with deep links for MCP setup, in …

chore: standardized procedures and documentation for creating issues with agents
