openameba/spindle

- .github/workflows/regression-test.yml
https://github.com/openameba/spindle/pull/47#issuecomment-709900109 にて発生したような、Pull-requestが発行されていないと比較対象が存在しないためreg-suitに新規追加だと思われてしまうというのを修正しているPRです。
mainブランチがpushされた時には必ず取得、他のブランチがpushされた時にはpathsをみて取得、と本当は書きたかったですがそういう指定ができそうになかったので仕方なくpush時にもpathsだけを指定するようにしました:cry:
たぶん大丈夫だと思うのですが……
それほど発生しないであろう状況なので、変更として良いのか悪いのか、どうしたものかという気持ちではあります🤔
> chore: take screenshot when push

- .github/workflows/version.yml
[なんかchangelogが内容出なくておかしいなぁ](https://github.com/openameba/spindle/blob/main/packages/spindle-icons/CHANGELOG.md)と思っていましたが、actions/checkout@v2だと効率化されて[デフォルトでは1コミットしかチェックアウトせず](https://github.com/actions/checkout#whats-new)、コミットメッセージからchangelogが作成できないようでした。
ケースバイケースでどこまで取得したらいいのかわからないので、versioningのタスクではすべての履歴を取得するように変更しました。
お試しで実行してみた結果は、以下で確認できます。
https://github.com/openameba/spindle/runs/1296647860?check_suite_focus=true
> chore: checkout with all history to generate changelog

- README.md
横幅の狭いディスプレイでロゴが縦長になってしまうのを解決しました。
本来は `style="height: auto"` などつけてレスポンシブにするのがよさげさんですが、表示時に`style`は消されてしまうので`height`属性を消す方法で対応しました。
これにより、アスペクト比がない画像によるレイアウトシフトが発生しますがしかたなく・・:cry:
> chore: display logo on mobile screen

- .github/workflows/regression-test.yml
spindle-uiに変更を加えていないPRがmainブランチにマージされた場合にスクリーンショットが無になってしまうのを修正しました。
ただ容量は食いそうですが……
https://github.com/openameba/spindle/pull/60#issuecomment-716967897
> chore: take screenshot every time

- packages/spindle-ui/tsconfig.json
生成物にはいらない storyファイルが出力されていましたので、設定を変更しました。
> chore(spindle-ui): remove unnecessary files from dist directory

- .github/workflows/regression-test.yml
ここぞというところで画像比較がちゃんとできずにお騒がせしております🙇‍♂️
openameba/spindle内でのPull-requestではPull-request前に`push`で画像が生成・比較されるので大丈夫そうです。
forkされたリポジトリからのPull-requestでは`pull_request_target`で対応するようにしています。
ただ、`push`と`pull_request_target`と両方の条件が書いてあるので、openameba/spindle内からPull-requestを生成した時に二重にworkflowが走ってしまうので、`pull_request_target`を特定の条件の時は実行しないようにしています（reg-suitのコマンドのところのみ）。
という条件で大丈夫そうでしょうか……
close #66
> chore: fix regression test condition

- .github/workflows/release.yml
- lerna.json
やはりGitHub Actionで作られるタグやリリースだとそれらをトリガーにしたAction (今回の場合は `publishing` )が動かなさげさんなので、一つのactionとして作成してみました。
https://github.com/openameba/spindle/blob/c06619fd0b580baf9ba4e6776bf50b12f4077b54/.github/workflows/publish.yml#L3-L6
_ちなみにこのPull Requestは初めてCodespacesで作業してみましたが、普通にできました。_
> chore: add release workflow

- packages/spindle-ui/.npmignore
- packages/spindle-ui/package.json
- packages/spindle-ui/src/index.ts
Iconコンポーネントを`@openameba/spindle-ui/Icon`から取得できるように修正しました。
この変更により以下の形式でコンポーネントをimportできます。
```JavaScript
import { Clock } from '@openameba/spindle-ui/Icon';
```
or
```JavaScript
import { Icon } from '@openameba/spindle-ui';
const { Clock } = Icon;
```
---
```JavaScript
import { Checkbox } from '@openameba/spindle-ui/Form';
```
or
```JavaScript
import { Form } from '@openameba/spindle-ui';
const { Checkbox } = Form;
```
> Change module export setting

- packages/spindle-ui/bundlesize.config.json
これからコンポーネントが追加されていくので、`index.css`のファイルサイズバジェットをあげておきます。ホントはもっと大きくなりそうな気がしますが、このへんは都度調整していきます。
> perf(spindle-ui): increase size budget for css

- .github/workflows/release.yml
リリース作業で出たCHANGELOGとpackage.jsonの差分をデフォルトブランチに取り込む https://github.com/openameba/spindle/pull/74 を自動にしてみました〜。
> chore: workflow post publish

- packages/spindle-ui/src/Button/Button.css
ボタン内のテキストが拡大された時(ズームではなくフォントサイズ自体が大きくなった時)用にスタイルを更新しました。
仕様は #28 を参照ください。
close #28
> feat(spindle-ui): improve button style when text is scaling up

- packages/spindle-ui/src/Button/Button.css
すでに認証プロジェクトで導入済みのButtonの新しいステートパターンを適用しました。変更の理由は #13 を参照してください。
hoverが可能なブラウザ(IE以外のPCブラウザ)で表示されます。
PCブラウザクリック時とAndroid Chrome タップ時に表示されます。
PCブラウザでのキーフォーカス時、Android Chromeでは長く押した時に表示されます。
iOS Safariで表示されます。
close #13
> feat(spindle-ui): update button state pattern

- .eslintignore
https://github.com/openameba/spindle/pull/82#pullrequestreview-523924524 に書いた、publicディレクトリをeslintが検査してしまうのを修正するPRです。
```console
$ DEBUG=eslint:file-enumerator yarn run lint:script
```
を実行すると、どのファイルに対して何をしたかが確認できます。
> chore: ignore public directory

- packages/spindle-ui/.storybook/main.js
- packages/spindle-ui/package.json
- yarn.lock
アプリケーションで使っていくにつれ、横幅の確認も増えてきそうなのでviewportプラグインを入れました。(確か土岐さんもおすすめだったプラグインのはず)
DevTools開かずStorybook上で確認できそうです。
> chore(spindle-ui): add storybook viewport addon

- .github/workflows/build-icon.yml
- packages/spindle-icons/docs/design-doc.md
- packages/spindle-icons/scripts/get-icons.ts
[FigmaのWebhook](https://www.figma.com/developers/api#webhooks-v2-events)で、アイコンの更新が検知できそうなので、自動的に変更があったファイルのみアイコンを生成して、プルリクエストを送るようにしてみようと思います。
大まかなフローは以下の通りです。
- FigmaでIconの変更し、パブリッシュする (手動)
- Figmaが`LIBRARY_PUBLISH `イベントで登録したWebhookにデータを送信する (どこかに作る予定)
- 送られてきたデータをもとに[GitHub APIにPOST](https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#create-a-workflow-dispatch-event)する
- このPRに含まれる処理が動き、アイコンが作られ、PRが自動的に作られる (はず)
デフォルトブランチ取り込まないとworkflowが動かせなそうな感じがするので、取り込んだあと手動で動かしてみます。
その後、Figmaとつなぐ部分を作ろうと思います。
> Build icons via Webhook

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/Button/Button.tsx
https://github.com/openameba/spindle/pull/86#discussion_r518590065 での話し合いで、Buttonはサイズに関わらずmax-widthを持たず、文字サイズに合わせる or コンテナに対して横幅100%指定となりましたので、対応しました。
> feat(spindle-ui): add full width option to button

- packages/spindle-ui/src/Button/Button.css
Buttonのサイズと太さがドキュメントと合っていなかったため修正。
ref: https://spindle.ameba.design/57edc1abc/p/89add9-button/b/1952d0
`font-family` はglobalに指定されるであろう Spindle標準の指定を継承する前提にした。
> fix(spindle-ui): button size & weight

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/Button/Button.tsx
> feat(spindle-ui): add Icon with Text button

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Form/Checkbox.css
- packages/spindle-ui/src/Form/InputLabel.css
- packages/spindle-ui/src/Form/InvalidMessage.css
- packages/spindle-ui/src/Form/Radio.css
- packages/spindle-ui/src/Form/TextField.css
Spindleコンポーネントのサイズは相対的にしておきたいですが、呼び出し元のアプリケーションのベースサイズ指定の仕方は様々な可能性があるので、親から継承された値を元に相対的になるようにしてみました。
実際の値は、Firebase PreviewのStorybookをみていただくとよさげさんです。
https://ameba-spindle--pr60-feature-em-unit-ezmh38dl.web.app/?path=/story/button--large
具体的な検討事項は #11 に記載していますので、そちらも合わせて見ていただけると助かります。
こちらはより良い方法があるかもしれないので、ご意見ください！
close #11
> feat(spindle-ui): change sizes to relative units

- packages/spindle-ui/package.json
- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Form/Checkbox.css
- packages/spindle-ui/src/Form/InputLabel.css
- packages/spindle-ui/src/Form/Radio.css
- packages/spindle-ui/src/Form/TextField.css
- yarn.lock
ameba-color-palette.cssをv4にあげました。v3.0.0-beta.0からのアップデートだったので、`v3.0.0-beta.1`の変更点も対応しました。
https://github.com/openameba/ameba-color-palette.css/releases/tag/v3.0.0-beta.1
> Update color palette to v4

- packages/spindle-ui/.gitignore
[リリース後に自動でつくるPRにnpm用に移動したコンポーネントファイルが含まれてしまっていた](https://github.com/openameba/spindle/pull/95/files)ので、`.gitignore`に追加しコミットに含まれないようにしました。ローカルでビルドを試した場合にも同様にgit管理されないようになります。
> chore(spindle-ui): gitignore files for npm

- lerna.json
[ファイルに変更がないのに、変更のあるパッケージとして扱われてしまう現象](https://github.com/openameba/spindle/pull/96)を解決するために、[include-merged-tags](https://github.com/lerna/lerna/tree/main/commands/version#--include-merged-tags)を追加してmerge commitが含まれる(つまり変更点の取得時に無視される)対応をしました。
ローカルmainブランチにて
変更前
```
$ npx lerna changed
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Assuming all packages changed
@openameba/spindle-icons
@openameba/spindle-ui
lerna success found 2 packages ready to publish
```
変更後
```
npx lerna changed
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Looking for changed packages since @openameba/spindle-icons@0.6.0
@openameba/spindle-ui
lerna success found 1 package ready to publish
```
> chore: ignore merge commit to detect changes with lerna

- packages/spindle-ui/src/Button/Button.css
`-webkit-tap-highlight-color`用custom propertyのフォールバックが正しく指定されていなかったので、修正しました。
デフォルトの濃いやつになっていた。
指定したい薄いやつ。
> fix(spindle-ui): apply fallback -webkit-tap-highlight-color in Button

- packages/spindle-ui/src/Button/Button.css
`<Button>`のスタイルをNested CSS custom propertiesで上書きできるようにしていましたが、Spindleのスタイルをデフォルトとし、現時点では必要ないので、削除しました。必要に応じて将来的に戻ってくる可能性はあります。
一部Custom propertiesは残っていますのでその指定で上書きすることはできます。
> fix(spindle-ui): remove unnecessary nested CSS custom properties

- .github/workflows/release.yml
たびたび恐縮ですが、[baseブランチとの差分がなくてPRが作成されない](https://github.com/openameba/spindle/runs/1421936302?check_suite_focus=true#step:11:56)ので、明示的に`main`ブランチを指定しました。
この動作はおそらく以下の機能によるものだと思います。
> If an updated pull request no longer differs from its base it will automatically be closed and the pull request branch deleted.
https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md#new-features-1
> chore: set base branch to create PR after releasing

- packages/spindle-ui/.storybook/preview-head.html
- packages/spindle-ui/README.md
- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Button/Button.stories.mdx
実プロジェクトで利用するに当たり、IE11でも使えたほうが良いということでいくつか対応をしました。
- StorybookにIE11だけCSS custom propertiesのpolyfillを追加しました 89c9aa843e3d7346ea036dfa320705b4e1b62d55
- ブラウザサポートをドキュメント化しました 22f007e03b50608b0abbccfbb811256c4fad3d53
- IE11で`align-items: center` と`min-height`を併用すると中央配置されない問題を解決しました 6fc6a1380cface288f80d23b4f6e60f17c196b6a
StorybookのボタンをIE11で確認します。
close #103
> Thinking of IE 🤔

- examples/css-modules/index.html
- examples/css-modules/package.json
- examples/styled-components/index.html
- examples/styled-components/package.json
styled-componentとCSS Modulesをserveしたときにわかりやすいよう `index.html` を追加。
> chore(spindle-ui): add index.html to sample page

- packages/spindle-ui/package.json
- yarn.lock
`<DropDown>`でHooksを使うようになったので、互換性のあるReactバージョンで利用できるようにしました。
事前に動作確認したい場合は、読み込み元のプロジェクトで以下のように設定します。
```
yarn add herablog/spindle#chore/peer
```
```TypeScript
import { DropDown } from 'spindle/dist0/Form';
// 必要であればCSSも読み込む
export function SomeFunc() {
return (<DropDown><option>A</option></DropDown>);
}
```
> chore(spindle-ui): install React as peerDependencies

- packages/spindle-ui/src/index.ts
読み込み元のプロジェクトがTypeScript 3.8未満だと`export * as` が解決できないので、より広範囲のバージョンで使える記法に変更します。
(今回対応の部分に関しては新記法使うメリットもあまりないため)
> refactor(spindle-ui): export components for project using TS < v3.8

- packages/spindle-ui/src/LinkButton/LinkButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.stories.mdx
- packages/spindle-ui/src/LinkButton/LinkButton.tsx
- packages/spindle-ui/src/LinkButton/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
Buttonのスタイルを`<a>`要素で使いたい要望があるので、`<LinkButton>`として用意することにしました。 w/ @hiloki 
`<Button>` の中で分岐したり共通化できる部分はありそうですが、微妙に動作が異なるのと1コンポーネント毎に独立して管理する方向で進めたいので、あらたな1コンポーネントとして定義しています。
(共通化はあきらかに必要になったタイミングで進めたいと思います)
`<Button>`と異なり、`<LinkButton>`には`disabled`の機能は用意されていません。
また、同時進行されている #113  #117  #118 の内容も含まれています。
> feat(spindle-ui): add LinkButton

- packages/spindle-ui/src/Button/Button.tsx
- packages/spindle-ui/src/Form/Checkbox.tsx
- packages/spindle-ui/src/Form/DropDown.tsx
- packages/spindle-ui/src/Form/InputLabel.tsx
- packages/spindle-ui/src/Form/InvalidMessage.tsx
- packages/spindle-ui/src/Form/Radio.tsx
- packages/spindle-ui/src/Form/TextArea.tsx
- packages/spindle-ui/src/Form/TextField.tsx
- packages/spindle-ui/src/Form/ToggleSwitch.tsx
#115 の対応で、`className`を受け取らないコンポーネントは、TS利用時に分かるように変更しました。
`Omit`で対応してみたけど、他にいい方法あるかしら🤔
close #115
> refactor(spindle-ui): omit className from props in atomic components

- packages/spindle-ui/.storybook/main.js
- packages/spindle-ui/.storybook/preview.js
- packages/spindle-ui/package.json
- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
デザイン仕様ではOutlined Buttonの背景は透過なので対応した。
- Outlined Buttonの `background-color` を `transparent` に
- 背景色ごとのテストのため、Storybookに[BackgroundのAddon](https://storybook.js.org/docs/react/essentials/backgrounds)追加
> Outlined Buttonの背景を透過にする

- .github/workflows/release.yml
`peter-evans/create-pull-request@v3` は差分比較してくれれたり、新規ブランチ作ってくれたり便利なのですが、我々の用途的にlernaでpushされた`release/*`ブランチ差分のPRを作りたいだけなので、REST APIをcurlで実行する形に変更してみました。
> chore(spindle-ui): create PR with curl as the release last task

- .github/workflows/build-icon.yml
- .github/workflows/build.yml
- .github/workflows/deploy-ui-catalog.yml
- .github/workflows/regression-test.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
[lerna bootstrap内部の`yarn install`で不必要なyarn.lock差分が出てしまっていた](https://github.com/openameba/spindle/runs/1484909092?check_suite_focus=true)ので、CI上では、常に`--frozen-lockfile`が適用されるように変更しました。
> chore: apply frozen-lockfile to lerna bootstrap in CI

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/Button/Button.tsx
- packages/spindle-ui/src/LinkButton/LinkButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.stories.mdx
- packages/spindle-ui/src/LinkButton/LinkButton.tsx
Experimental なVariantとして、Buttonに `lighted` を追加しました。
- `neutral` からの状態変化先として使う
- 単独での利用は推奨しない
> feat(spindle-ui): add Lighted Button

- packages/spindle-ui/src/LinkButton/LinkButton.tsx
`type`で`Omit`と`forwardRef `併用すると`Pick<>....`と変換されてしまうので`interface`に変更しました。どっちみち`Props`は`interface`にしようかなと思っていたので、他のコンポーネントも別で変更予定です。(このパターンに該当するのは現状`<LinkButton>`だけ)
<details>
<summary>type</summary>
```TypeScript
import React from 'react';
export declare const LinkButton: React.ForwardRefExoticComponent<{
layout?: "intrinsic" | "fullWidth" | undefined;
size?: "small" | "medium" | "large" | undefined;
variant?: "contained" | "outlined" | "neutral" | "danger" | undefined;
icon?: React.ReactNode;
} & Pick<React.AnchorHTMLAttributes<HTMLAnchorElement>, "media" | "hidden" | "dir" | "slot" | "style" | "title" | "color" | "children" | "type" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | "accessKey" | "contentEditable" | "contextMenu" | …
```
> fix(spindle-ui): avoid inaccurate type in LinkButton

- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/IconButton/IconButton.stories.mdx
- packages/spindle-ui/src/IconButton/IconButton.test.tsx
- packages/spindle-ui/src/IconButton/IconButton.tsx
- packages/spindle-ui/src/IconButton/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
[`<IconButton>`コンポーネント](https://spindle.ameba.design/57edc1abc/p/89add9-button/b/1952d0/t/807d56)を作成しました。こちらは一つのアイコンが入ることのみ想定したボタンです。
https://ameba-spindle--pr81-feat-icon-button-7xpem25g.web.app/?path=/docs/iconbutton--large
> feat(spindle-ui): add IconButton component

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Form/Checkbox.css
- packages/spindle-ui/src/Form/DropDown.css
- packages/spindle-ui/src/Form/Radio.css
- packages/spindle-ui/src/Form/TextArea.css
- packages/spindle-ui/src/Form/TextField.css
- packages/spindle-ui/src/Form/ToggleSwitch.css
フォーカススタイルを[:focus-visibleに対応しているブラウザ](https://caniuse.com/css-focus-visible)にはそちらで、対応していないブラウザには今まで通り:focusで指定するように変更しました。
確認するときは実際タップ、タブ移動して見る他、Chrome DevToolsの「Force element state」機能がおすすめです。
> feat(spindle-ui): set focus style with focus-visible

- packages/spindle-ui/src/ButtonGroup/ButtonGroup.css
- packages/spindle-ui/src/ButtonGroup/ButtonGroup.stories.mdx
- packages/spindle-ui/src/ButtonGroup/ButtonGroup.tsx
- packages/spindle-ui/src/ButtonGroup/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
[ボタンを組み合わせて](https://spindle.ameba.design/57edc1abc/p/89add9-button/b/23f24c)使うときのために、`<ButtonLayout>` コンポーネントを作成しました。
実際どれくらい使われるかは不明ですが、きれいにボタンが並んで便利な感じはします:eyes:
> feat(spindle-ui): add ButtonGroup component

- .github/workflows/build-icon.yml
- packages/spindle-icons/package.json
Iconの自動更新(追加/更新)では、ディレクトリのcleanupは必要ないので、オプショナルとして実行するようにしました。これで、[関係のないファイルまで消されてしまう問題](https://github.com/openameba/spindle/pull/93/files)が解消されると思われます。
※ 削除対応は別途します。
ref: #133
> chore(spindle-icons): make preparation task optional

- packages/spindle-ui/package.json
- packages/spindle-ui/src/Button/Button.test.tsx
- packages/spindle-ui/src/Button/Button.tsx
- packages/spindle-ui/src/Form/Checkbox.test.tsx
- packages/spindle-ui/src/Form/Checkbox.tsx
- packages/spindle-ui/src/Form/DropDown.test.tsx
- packages/spindle-ui/src/Form/DropDown.tsx
- packages/spindle-ui/src/Form/InputLabel.tsx
- packages/spindle-ui/src/Form/InvalidMessage.tsx
- packages/spindle-ui/src/Form/Radio.test.tsx
- packages/spindle-ui/src/Form/Radio.tsx
- packages/spindle-ui/src/Form/TextArea.test.tsx
- packages/spindle-ui/src/Form/TextArea.tsx
- packages/spindle-ui/src/Form/TextField.test.tsx
- packages/spindle-ui/src/Form/TextField.tsx
- packages/spindle-ui/src/Form/ToggleSwitch.test.tsx
- packages/spindle-ui/src/Form/ToggleSwitch.tsx
- yarn.lock
BREAKING CHANGE: Components have different behavior after using React.forwardRef
https://reactjs.org/docs/forwarding-refs.html
---
後回しにしていた[Forwarding Refs対応](https://reactjs.org/docs/forwarding-refs.html)をしました。利用プロジェクトが増えつつあるので、早めに対応しておこうという意図になります。
本来はBREAKING CHANGEでメジャーバージョンを上げるべきですが、
> Spindle UIは試験開発中のため、大幅に変更される可能性があります。安定版リリースまでの間はバージョン番号は0となり、バージョンに関わらずbreaking changeが行われることがありますので、利用時には注意してください。
https://github.com/openameba/spindle/blob/main/packages/spindle-ui/README.md
のため、同一メジャーバージョンでリリース予定です。(そろそろ仕様・利用法が固まりそうなので、もろもろ含めてv1になるかも)
> feat(spindle-ui): forward ref to interactive components

- packages/spindle-ui/src/IconButton/IconButton.css
outlined `<IconButton>` の背景が透過になっていなかったので、対応しました。
ref: https://github.com/openameba/spindle/pull/121
> fix(spindle-ui): set background transparent to outlined icon button

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
やはりボタンのスタイルを特定用途のみカスタマイズしたい要望があるので、カスタムプロパティで指定できるようにしていました。[前回](https://github.com/openameba/spindle/pull/106)と異なり、nestedな値ではなく再代入方式にしたので、より様々なパターンで使えるようになったと思われます。もともとデザイン時に @MasatoHonda とは「ボタンのスタイルはカラーパレットに従っているけど実際には固有」と話していたことがあるので、その設計通りのコードにはなったかなという感じです。
この変更はmainに入れず、どっかのバージョンのbetaとして動作確認してみようかとおもってます。
ameba-color-palette.css (`--color-*`) 自体を上書きします。
```css
:root {
--color-surface-accent-primary: red;
...
}
```
ボタンのカスタムプロパティ`--Button`を上書きします。
```css
:root {
--Button--contained-backgroundColor: red;
...
}
```
直近の親要素などスコープを絞った状態で、ボタンのカスタムプロパティ`--Button`を上書きします。
```html
<div class="extra-button"><button class="spui-button"></button></div>
```
```css
.extra-button {
--Button--contained-backgroundColor: red;
...
}
```
Nestedなカスタムプロパティだとうまく動作しない場合もありましたが、代入方式だとうまく変換される気がします (手元で試したところ) …
> feat(spindle-ui): CSS custom property experiment

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Form/DropDown.css
- packages/spindle-ui/src/IconButton/IconButton.css
`<button/>` のUAのmarginによってズレが発生するのを修正。
> fix(spindle-ui): remove the margin in Firefox and Safari

- packages/spindle-ui/CHANGELOG.md
- packages/spindle-ui/package.json
- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
利用プロジェクトでの動作確認が取れたので、CSS custom property対応をmainブランチに取り込みます。取り込まれた後、本リリース(v0.12.0)をおこないます。
詳細の変更内容は #132 を参照ください。
@hiloki ちなみに、`transitionDuration`と`onDisabled-opacity`は変更できなくてもいいような気がしてきたんですが、どう思います？
https://github.com/openameba/spindle/blob/91c1f13f4a6f0c91cc6daec29a17c557bc6bb0d8/packages/spindle-ui/src/Button/Button.css#L7-L8
> Expose CSS custom property for Button components

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Form/Checkbox.css
- packages/spindle-ui/src/Form/DropDown.css
- packages/spindle-ui/src/Form/Radio.css
- packages/spindle-ui/src/Form/TextArea.css
- packages/spindle-ui/src/Form/TextField.css
- packages/spindle-ui/src/Form/ToggleSwitch.css
- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
resolve: #156 
Browsers that do not support `:focus-visible` will disable all grouped selectors that contain `:focus-visible`.
See also https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible#selectively_showing_the_focus_indicator
```css
custom-button {
display: inline-block;
margin: 10px;
}
custom-button:focus {
/* Provide a fallback style for browsers
that don't support :focus-visible */
outline: none;
background: lightgrey;
}
custom-button:focus:not(:focus-visible) {
/* Remove the focus indicator on mouse-focus for browsers
that do support :focus-visible */
background: transparent;
}
custom-button:focus-visible {
/* Draw a very noticeable focus style for
keyboard-focus on browsers that do support
:focus-visible */
outline: 4px dashed darkorange;
background: transparent;
}
```
> Fix hidden focus indicator by not support focus-visible browser

- packages/spindle-ui/src/LinkButton/LinkButton.css
とあるプロジェクトでLinkButtonを使用していたところ、変数名の間違いを見つけたのでそれを修正しました。
> fix(spindle-ui): fix CSS variable name

- package.json
- yarn.lock
`lerna` v4と`@commitlint/config-lerna-scopes` v12.1.0未満を使用するとエラーが発生し、コミットができなくなっていたので`@commitlint`系モジュールをアップグレードしました。
ref: https://github.com/conventional-changelog/commitlint/issues/2452
close #171
> chore: upgrade commitlint modules

- packages/spindle-icons/README.md
- packages/spindle-icons/example/index.html
Spindle Iconsのサンプルページをアップデートしました。
- READMEから参照できるようにしました
- 表示できていなかったアイコンを表示しました
- インラインSVGでの利用法を追加しました
> docs(spindle-icons): update example page

- packages/spindle-ui/.storybook/preview-body.html
- packages/spindle-ui/.storybook/preview-head.html
- packages/spindle-ui/src/Toast/Toast.stories.mdx
https://github.com/openameba/spindle/pull/231 で追加したToastコンポーネントのstorybookに、アクセシビリティ周りのコードを付け足しました。
背景としては、今の状態だとアクセシビリティ対応をどのように行えば良いかぱっと見ではわからないためです。
ref: #232
> docs: add accessibility example for Toast component

- packages/spindle-ui/src/Toast/Toast.css
`prefers-reduced-motion`を明示的に宣言するように修正しました。
- https://github.com/openameba/spindle/pull/242#discussion_r668586661
> refactor(spindle-ui): fix prefers-reduced-motion to be declared explicitly

- packages/spindle-tokens/CHANGELOG.md
- packages/spindle-tokens/package.json
`@openameba/spindle-tokens` がリリースされました。
> chore(release): publish

- packages/spindle-tokens/lib/output-styles-as-style-dictionary.test.ts
- packages/spindle-tokens/lib/output-styles-as-style-dictionary.ts
主にネイティブアプリ用のデザイントークンファイルを作る際に、カテゴリごとにフィルタリングする用途がありそうなので、Style Dictionary用のJSONに`attributes: { category: 'color' }`を付与しました。これにより書き出すJSONにもカテゴリが追加されます。
https://github.com/amzn/style-dictionary/blob/4ff8a2d9298d430fcafcf4403fc25fd3e36c7cb6/lib/common/formats.js#L538-L541
> feat(spindle-tokens): add category to color tokens

- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/IconButton/IconButton.stories.mdx
`Button` のバリエーションにあった `Lighted` を本番採用するコンポーネントにするため、Storybook上の試験中扱いのバッジを削除した
fix: #164
> Lightedから試験中ステータスを削除

- packages/spindle-ui/src/Form/InvalidMessage.css
- packages/spindle-ui/src/Form/InvalidMessage.tsx
InvalidMessageコンポーネントがデザイナさんが想定していたものと相違があったため以下修正を行いました。
- 行数が増えると1行目と2行目の行間が以降の行間と比べ広くなっていた
- 複数行の場合、行初めの開始位置を揃える
- before
- after
> fix(spindle-ui): adjust style of InvalidMessage

- packages/spindle-syntax-themes/package.json
`npx serve`のデフォルトポートが5000から3000番に変更されていたので、5000で固定するようにしました。
https://github.com/vercel/serve/releases/tag/13.0.0
mainブランチでテストが通らなくなっていたのは、acotでlocalhost:5000を見ようとしていたからのようです。
> chore: fix server port

- .github/workflows/regression-test.yml
regression test内の`npx serve`のポートを5000に固定しました。
ref: https://github.com/openameba/spindle/pull/304
> chore: fix serve port for regression-test

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
ボタンで指定するトークンが間違っていたので修正しました。
結果的にはOutlinedボタンのテキスト色がコントラスト比改善する方向に、Lightedボタンのアイコンがオブジェクト用のコントラスト比に変更されました。
それ以外に色の変更はなさそうです。
> fix(spindle-ui): correct button tokens

- .eslintrc.json
- packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
- packages/spindle-ui/src/HeroCarousel/HeroCarousel.stories.mdx
- packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
- packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
- packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
- packages/spindle-ui/src/HeroCarousel/hooks/useAutoPlayCarousel.ts
- packages/spindle-ui/src/HeroCarousel/hooks/useAutoSlide.ts
- packages/spindle-ui/src/HeroCarousel/hooks/useCarouselFocus.ts
- packages/spindle-ui/src/HeroCarousel/hooks/useSliderMoveEvent.ts
- packages/spindle-ui/src/HeroCarousel/hooks/useSliderTransition.ts
- packages/spindle-ui/src/HeroCarousel/hooks/useValueRef.ts
- packages/spindle-ui/src/HeroCarousel/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
HeroCarouselコンポーネントを追加しました
最近Ameba Newsで作られたカルーセルが最も最新かつアクセシビリティ要件も考慮されたものだったので、そちらの実装を(基本的には)丸っと持ってきています
本PRの背景とゴールについてはこちら: https://github.com/openameba/spindle/pull/348#issuecomment-1043701618
HeroCarouselに渡せるPropsは以下です
- [必須]`carouselList`
- [必須]`imageUrl`(string)
- [必須]`link`(string)
- [必須]`title`(string): 2行以上は省略(全角だと18文字までは表示 / 19文字以降は省略される)
もっと細かく設定できるようにしたいのですが、今回のチームの案件は上記で足りるため一旦ミニマムで行きます！
※ 今後HeroCarouselを使う際に不足あるようでしたら、都度足していければと思います :pray
諸々の都合上関連リンクを貼れないため、このPRの作成通知が流れるSlackのスレに貼ります 🙏🏻 
ref: https://github.com/openameba/spindle/discussions/336
> HeroCarouselを追加

- packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
- packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
https://github.com/openameba/spindle/pull/348 で追加したHeroCarouselコンポーネントの軽微な修正です
Storybookで確認する分には上記のPRの実装で問題なかったのですが、使用したいページでいざ読み込んで使おうとしたら微妙にレイアウトが崩れていたので対応しました
主な原因: AmebaNewsからコードを移植してくる際に(Storybookで確認する分には)指定しなくて良さそうなスタイルを消したのですが、実はそれが必要だったっぽいです
1. スライド部分が中心より左にずれる→ 横幅を指定して対応: https://github.com/openameba/spindle/commit/3021f531d9247bb3893fbb4069c1ac35a97b36f5
| before | after |
| -- | -- |
| ![スクリーンショット 2022-02-22 18 18 24](https://user-images.githubusercontent.com/42470015/155107154-0fa2e00b-6bac-4172-bebc-9024cf128664.png) | ![スクリーンショット 2022-02-22 18 51 48](https://user-images.githubusercontent.com/42470015/155107294-e33773a3-2893-4e07-8b49-2d6300a15823.png) |
2. Controlsのサイズが微妙に大きい → 各controlにサイズを当てるのではなく、controls全体にサイズを指定して対応。また、アイコンのサイズが常に一定になるように対応: …
> fix HeroCarousel component 

- packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
- packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.tsx
`HeroCarousel`内で利用される`HeroCarouselItem`で JS 内から CSS を import しないようにし、`HeroCarousel.css` の中で読み込むようにしました。
Next.jsで利用する場合に [CSS の読み込みが上手くいかずエラーとなってしまう](https://nextjs.org/docs/messages/css-npm)ため、その修正です。
> fix(spindle-ui): do not use CSS import in JS

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.css
- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
- packages/spindle-ui/src/Breadcrumb/BreadcrumbItem.tsx
- packages/spindle-ui/src/Breadcrumb/BreadcrumbList.tsx
- packages/spindle-ui/src/Breadcrumb/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
[Amebaのサイト](https://about.ameba.jp/contents/ed88wdx61mf1/)を元にパンくずリスト(Breadcrumb)を作成しました。今後新たなスタイルが出てきた場合にはvariantを追加する予定です (@MasatoHonda 相談済み)。
Storybook: https://ameba-spindle--pr361-feat-breadcrumb-4o86l7i2.web.app/?path=/story/breadcrumb--breadcrumb-list
anchorの要素がサービスによって異なりそうなので、ブランドサイトと違い子コンポーネントを受け取る形にしようと思います。
詳しくは https://raw.githubusercontent.com/openameba/spindle/feat/breadcrumb/packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
```js
<BreadcrumbList>
<BreadcrumbItem href="#">Top</BreadcrumbItem>
<BreadcrumbItem href="#">Team</BreadcrumbItem>
<BreadcrumbItem>Amebaとは</BreadcrumbItem>
</BreadcrumbList>
```
※ ListとItemは一緒に利用する可能性が高いので、`Breadcrumb.List`, `Breadcrumb.Item`でのexportを考えていましたが、List単体でも利用できるかつ、利用側で`Breadcrumb.Item`をバンドルから外しにくなってしまうため、それぞれexportするようにしました。
※ …
> feat(spindle-ui): add Breadcrumb component

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.css
Breakpointが375pxになっていたので修正しました
memo: 元実装のレスポンシブ対応の時に値が更新されました
> fix(spindle-ui): fix breadcrumb breakpoint

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/package.json
- yarn.lock
Spindle UIで使うameba-color-palette.cssを最新版にしました。
> chore(spindle-ui): update ameba-color-palette.css

- packages/spindle-ui/src/Toast/Toast.stories.mdx
[アクセシビリティガイドライン](https://a11y-guidelines.ameba.design/1/1/1/#web)の「不可視のテキスト要素を用意し、支援技術にはアイコン自体を無視させる方法」を参考にして CSS の推奨されるコード例を storybook の docs に追加しました。
> Add polite announcer css example to storybook docs

- packages/spindle-ui/src/SubtleButton/SubtleButton.css
- packages/spindle-ui/src/SubtleButton/SubtleButton.stories.mdx
- packages/spindle-ui/src/SubtleButton/SubtleButton.tsx
- packages/spindle-ui/src/SubtleButton/index.ts
- packages/spindle-ui/src/index.css
`<SubtleButton>`をSpindle UIに追加しました。
独立して定義されているため、従来の`<Button>`とは別に定義しました。
[Spindleサイト](https://spindle.ameba.design/components/button/#Subtle-Button)にはまだ反映されていないですが、対象Figmaのスクリーンショットを載せておきます。
> feat(spindle-ui): create SubtleButton

- packages/spindle-ui/src/ButtonGroup/ButtonGroup.css
- packages/spindle-ui/src/ButtonGroup/ButtonGroup.stories.mdx
`<ButtonGroup>`をアップデートしました。内容は以下のとおりです。
- 余白指定のリファクタ [462e945](https://github.com/openameba/spindle/pull/408/commits/462e945cda44dd58e635d66af242ec235b1e6bd7) reg-suitで差分出ていないので大丈夫かと思われです
- Subtleボタンを想定したスタイルにアップデート [896c6e5](https://github.com/openameba/spindle/pull/408/commits/896c6e5d8a52e0120d467f18421b9ba4b0502262) Subtleボタンはcolumnレイアウトのときのみスタイルが当たります
> refactor(spindle-ui): improve margin style

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.css
- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/HeroCarousel/HeroCarousel.css
- packages/spindle-ui/src/HeroCarousel/HeroCarouselItem.css
- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
#393 に関連して、今の動作を変えないまま実装を`box-shadow`から`outline`に変更しました。
```css
box-shadow: 0 0 0 1px var(--color-surface-secondary),
0 0 0 3px var(--color-focus-clarity);
```
3pxの青い線を敷いてその上に1pxの白乗せてオフセット作ってます。
```css
outline: 2px solid var(--color-focus-clarity);
outline-offset: 1px;
```
Safariは角丸のoutlineに対応していないので四角くなってしまいますが、 @MasatoHonda 認識済みです。
- 対象コンポーネントのfocus動作をStorybookで検証します (Chrome, Firefox, Safari)
close #393
> Style focus with outline

- packages/spindle-tokens/lib/output-styles-as-style-dictionary.test.ts
- packages/spindle-tokens/lib/output-styles-as-style-dictionary.ts
Style Dictionaryでサイズとして認識したい項目にカテゴリを追加しました。
https://amzn.github.io/style-dictionary/#/transforms?id=sizepx
> feat(spindle-tokens): add size category to shadow token

- packages/spindle-ui/src/ButtonGroup/ButtonGroup.css
SubtleButtonの余白が変更になったので、対応しました。
- large: 20px
- medium, small: 14px
> fix(spindle-ui): change ButtonGroup margin for SubtleButton

- packages/spindle-ui/src/TextLink/TextLink.css
様々なアプリでの利用(resetなどで消える場合)を考慮して、デフォルトのunderlineを指定します。
> fix(spindle-ui): set default underline style to TextLink

- packages/spindle-ui/src/IconButton/IconButton.css
IconButtonコンポーネントをiOSで見た時にアイコンが表示されてないバグの修正です。
iOSブラウザだとbuttonタグにpaddingが付与されていたため、中のアイコンが小さくなってしまったようです。
- close #430 
シミュレーターで表示されることを確認しました
> fix(spindle-ui): svg icon disappears on iOS

- packages/spindle-ui/src/List/MoreLink.css
- packages/spindle-ui/src/List/MoreLink.stories.mdx
- packages/spindle-ui/src/List/MoreLink.tsx
- packages/spindle-ui/src/List/index.css
- packages/spindle-ui/src/List/index.ts
- packages/spindle-ui/src/index.css
MoreLinkをSpindle UIに追加しました。
Listの一部のため、Listディレクトリを切って追加しています。
focusやtap-highlight-colorが定義されてなかったので既存に合わせて実装しましたが、このPR上で調整したいと思います。
notion: https://www.notion.so/cyberagent/List-MoreLink-e0cd6ef664894a338a578a5ae12997f2
ホバー時のデザイン
> feat(spindle-ui): create MoreLink

- packages/spindle-ui/bundlesize.config.json
Spindle UIとしてはESM版をプライマリとして提供している(お気持ち)ので、サイズチェックをそちらのスクリプトベースでするように変更しました。同時に今のサイズに合わせてバジェットを更新しています。
> chore(spindle-ui): check ESM file size

- packages/spindle-ui/src/Dialog/Dialog.css
- packages/spindle-ui/src/Dialog/Dialog.tsx
Dialogに開閉アニメーションを追加しました。以下のアニメーションで @MasatoHonda と確認済みです。
- 開く時: 350msの`cubic-bezier(0, 0, 0, 1)`, ゆっくり目にふわっと出現する (早すぎない情緒的なAmebaらしさ)
- 閉じる時: 150msの`cubic-bezier(0, 0, 0, 1)`, 視界のじゃまにならない程度に早めに消える
なおアニメーションは後々トークン化される予定です。
- 開く時と閉じる時のアニメーションを定義しました
- 閉じる時にはアニメーションの終了を待って、`onClose`イベントを発行します
確認URLはこりがよさそうです。
https://ameba-spindle--pr441-feat-dialog-animatio-ac4xxfx5.web.app/iframe.html?id=dialog--normal&viewMode=story
> feat(spindle-ui): add animation to Dialog

- packages/spindle-ui/src/Modal/AppealModal.stories.mdx
`AppealModal`のdocsにあるCSSのCDNリンクが正しくなかったため修正しました
> docs: modify CDN stylesheet link URL

- packages/spindle-icons/tsconfig.json
[アイコンのビルドが失敗](https://github.com/openameba/spindle/actions/runs/2661459157)していたので対応しました。[ts-node実行時](https://github.com/openameba/spindle/blob/4714a55f45348a04ef5468f3eba255eaa04f0f18/packages/spindle-icons/package.json#L8)に型エラーが出てたので共通のconfigを読み込むようにしてみました(前は参照できてたんだろか？[-Tオプション](https://typestrong.org/ts-node/docs/options#transpileonly)でもいいですがconfigはあってよさそうなため〜)。
その結果[ジョブは成功するようになりました](https://github.com/herablog/spindle/runs/7317222029?check_suite_focus=true)。
_より良い解決方法があればそりでいきたいです！_
> build(spindle-icons): set tsconfig to build

- .renovaterc.json
https://github.com/openameba/spindle/pull/451 で修正したrenovateの問題ですが、`config:base`で`prConcurrentLimit`が10に設定されているのが原因でした。
Spindleは活発に開発され続けるRepositoryなはずなので`prConcurrentLimit`を0にして制限を無くしました。
またassigneeに`@hiloki`さんが入っていたので外しました
> chore: fix renovate config

- packages/spindle-ui/package.json
- yarn.lock
[Paginationコンポーネント](https://github.com/openameba/spindle/pull/440/files#diff-74e7487d3abc00979125f224d0bf210fe7662e14bfbef010e5e754037080ea8cR1)のテストでhooksを使いたかったため追加しました。以前は特にエラーが出ていなかったのですが最新のmainブランチを取り込んだ際にエラー出てしまい。
[jestのバージョンあがった](https://github.com/openameba/spindle/pull/473)あたりが影響してるのだろか。
> feat(deps): testing library react hooks

- .eslintrc.json
- package.json
- packages/spindle-ui/src/HeroCarousel/HeroCarousel.tsx
- yarn.lock
ESLintプラグインの[`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks)を追加しました。
これにはhooksの依存の整合性を検知する`react-hooks/exhaustive-deps`などのルールが含まれており、実装レビュー時の見落としを防ぐために導入します。
`react-hooks/rules-of-hooks`によるError1件のみ、変更内容が軽微でもあるためコンポーネントの修正を追加しています：https://github.com/openameba/spindle/commit/d1b3eea6a7bf3be8549e3b48020b2b5062228955
そのほか`react-hooks/exhaustive-deps`によるWarningが複数発生しますが、この修正は差分が大きくなるほか、コンポーネントの機能に関わる可能性もあるため、別PRで対応することにします。
> chore(deps): add eslint-plugin-react-hooks

- packages/spindle-ui/src/TextButton/TextButton.stories.mdx
Subtle With Icon（TextButton）のドキュメント通りに実装すると意図した表示と違う見栄えになったので、ドキュメントを修正しました 🚀 
→ `variant="subtle"`が足りていなさそうでした 🙏🏻 
| Before | After |
| -- | -- |
| ![スクリーンショット 2022-08-21 22 57 30](https://user-images.githubusercontent.com/42470015/185794507-461f422c-b787-4652-8bf3-e20ebfbe3e7e.png) | ![スクリーンショット 2022-08-21 22 58 18](https://user-images.githubusercontent.com/42470015/185794535-0f62cae6-a59c-4f04-a54c-eeb0ab1795d5.png) |
> update TextButton docs

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.css
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.stories.example.tsx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.stories.mdx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.test.tsx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.tsx
- packages/spindle-ui/src/DropdownMenu/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
DropdownMenuコンポーネントを作成しました 🚀 
DropdownMenuは、全部で4パターンあります
| Textのみパターン | Icon + Textパターン（1line 44px） | Icon + Headパターン（1line 56px） | Icon + Head + Captionパターン |
| -- | -- | -- | -- |
| ![スクリーンショット 2022-08-10 14 52 16](https://user-images.githubusercontent.com/42470015/183825826-cd035e64-c2c6-4dde-a7d3-3e468b53372d.png) | ![スクリーンショット 2022-08-10 14 52 22](https://user-images.githubusercontent.com/42470015/183825847-586542eb-398c-4e5d-b5c3-e9dd86e16582.png) | ![スクリーンショット 2022-08-10 14 52 28](https://user-images.githubusercontent.com/42470015/183825880-06209c18-76ad-4a64-92f2-acc3d2937281.png) | ![スクリーンショット 2022-08-10 14 52 34](https://user-images.githubusercontent.com/42470015/183825914-171fd71a-4e23-4877-a0fa-f37d78b75b8d.png) |
上記の例ではTriggerボタンに対して右側にMenuを開いていますが、左に開くことも可能です …
> add DropdownMenu component

- packages/spindle-ui/jest.config.js
- packages/spindle-ui/package.json
- packages/spindle-ui/src/Dialog/Dialog.tsx
- packages/spindle-ui/src/Form/DropDown.tsx
- packages/spindle-ui/src/Form/InlineDropDown.tsx
- packages/spindle-ui/src/Modal/AppealModal.tsx
- packages/spindle-ui/tsconfig.json
- yarn.lock
https://github.com/openameba/spindle/pull/477 こちらのPRの取り戻しです
ESMのみの対応になったことで、ESM未対応のプロダクトで利用する際に問題があったため、暫定対応としてパッケージのバージョンを元に戻します
改めてバージョンを上げる際には、ESMのパッケージはCJSにトランスパイルして配信するか、利用側のESM対応が前提である場合とします
ref：https://github.com/openameba/spindle/pull/477#issuecomment-1231077349
> fix(deps): revert version of react-merge-refs to v1

- .renovaterc.json
renovateのPRの数が多くて捌ききれないのでlinter系とtest系はautomergeを設定します。
> chore: use renovate automerge for linter and test

- packages/spindle-theme-switch/README.md
- packages/spindle-theme-switch/src/spindle-theme-switch.ts
ダークテーマ選択時に[タップエリアを広げる処理](https://github.com/openameba/a11y-guidelines/pull/260)が動作していなかったため、修正しました。
本PRではできるだけ範囲を絞り「ダークテーマ選択時のみタップエリアの要素を選択中を表す背景要素より上にする」対応をしています。いくつか改善方法がありそうなので、提案絶賛募集中です 🐗 
対応前: https://ameba-spindle-theme-switch.web.app/
https://user-images.githubusercontent.com/869023/187384899-6b702a3c-44ec-48ca-9951-9b3fb34cec95.mov
対応後: https://ameba-spindle-theme-switch--pr520-fix-switch-1kn7zyh2.web.app/
https://user-images.githubusercontent.com/869023/187384992-c316cb03-254b-427c-a281-d4c37d5740e3.mov
> fix(spindle-theme-switch): expand tap area

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.css
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.stories.example.tsx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.stories.mdx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.tsx
https://github.com/openameba/spindle/pull/502 で実装したDropdownMenuを拡張しました 🚀 
当初はTriggerボタンに対してMenuを左に開くか右に開くかの用途しかありませんでした
しかし、現在進行形の施策にて新たに上下にも開きたいという要望が出たので、新たに上下左右4方向 × 左右中央寄せ3パターンの計12パターンを指定できるように拡張しました
加えて、TriggerボタンとMenuの間を8px開けて欲しいとデザイナーさんから依頼があったので、そちらの対応もしています
`position`プロパティに、menuをボタンに対してどの位置に開くかを指定できます
デフォルトは`leftTop`で、その他にも`topLeft`, `topCenter`, `topRight`, `rightTop`, `rightCenter`, `rightBottom`, `bottomLeft`, `bottomCenter`, `bottomRight`, `leftTop`, `leftCenter`, `leftBottom`を指定することができます
（画像にまとめてみました👇）
某チームの施策内で使いたいとのことですので、10/4(火)あたりには完了できていると嬉しいです
関連リンクに関してはSlackの通知スレに貼ります
> Expand dropdown menu

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/src/Pagination/Pagination.css
- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.test.tsx
- packages/spindle-ui/src/Pagination/Pagination.tsx
- packages/spindle-ui/src/Pagination/PaginationItem.css
- packages/spindle-ui/src/Pagination/PaginationItem.tsx
- packages/spindle-ui/src/Pagination/hooks/useItemPageNumber.test.ts
- packages/spindle-ui/src/Pagination/hooks/useItemPageNumber.ts
- packages/spindle-ui/src/Pagination/hooks/useShowItem.test.ts
- packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
- packages/spindle-ui/src/Pagination/index.ts
- packages/spindle-ui/src/index.css
ページ間の移動を目的として使用されることを想定したページネーションを追加しました。
- 現在のページが**1**でページ総数も**1**の場合
- 現在のページが**1**でページ総数が**2**以上ある場合
- 現在のページとページ総数が**同じ**場合
- currntに対して前後いくつのページ番号を表示するかはpageItems（**3** or **5**）で指定することができる default値は**3** に加えて上記のパターンを考慮する
- url: string;（リンクに渡すURL）
- urlには必ずPAGA_NUMBER渡しこれが遷移するページ数に変換されます
- current: number;（現在のページ）
- total: number;（ページ総数）
- showCount?: boolean;（現在のページ数と総ページ数のカウントを表示するか否か）
- showPrevNext?: boolean;（前へ次へアイコンを表示するか否か）
- showFirstLast?: boolean;（最初へ最後へアイコンを表示するか否か）
- onPagination?: (event: any, pageNumber: number) => void;
- ページ番号をクリックした際はそのページ番号を返却
- 「前へ」ボタンクリック時はcurrnt - 1を返却
- 「次へ」ボタンクリック時はcurrnt + 1を返却
- 「最初へ」ボタンクリック時は1を返却
- 「最後へ」ボタンクリック時はtotal（ページ総数）を返却
- onCreateUrl?: (pageNumber: number) => string;
- 関数を渡すことでURLを任意の形で生成
- aria-label
- aria-current
> feat(spindle-ui): add pagination component

- .github/workflows/release.yml
- packages/spindle-ui/src/Pagination/Pagination.css
- packages/spindle-ui/src/Pagination/PaginationItem.css
Paginationのstyleで一部不具合があったため修正しました。
おそらくコンポーネントを作っている間にもれが発生していたようで。
focus時のstyleが少しズレている
少しわかりづらいですが最初への矢印が消えるはずが残っており画面からはみ出している
https://ameba-spindle.web.app/?path=/story/pagination--current-8-total-20
> fix(spindle-ui): pagination style

- packages/spindle-ui/README.md
- packages/spindle-ui/src/BottomButton/BottomButton.stories.mdx
- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
ほとんどのコンポーネントのdocsにて、import文が個別インポート👇ではなく
```
import { Button } from '@openameba/spindle-ui/Button';
```
spindle-ui丸ごとインポート👇になっていたので変更しました 🚀 
```
import { Button } from '@openameba/spindle-ui';
```
修正としては特に急ぎではないですが、docsを正しい状態にするという意味ではなるはやだと嬉しいです！
> docs(spindle-ui): stopped global import

- packages/spindle-ui/CHANGELOG.md
- packages/spindle-ui/src/Breadcrumb/Breadcrumb.css
- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
- packages/spindle-ui/src/Breadcrumb/BreadcrumbList.tsx
Breadcrumbに新しいvariantが追加されたので対応しました。この変更によりdefault variantが変更されるため、Breaking changeとなります。
- VariantがStandardとEmphasizedの2種類になりました
- overflowした部分はスクロール表示になりました
- overflowした場合には、現在地(current)がviewport内に表示されます
- Standardにwrapオプションを指定すると折返します
> feat(spindle-ui): add Breadcrumb variants

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
利用時に、`Breadcrumb[variant=standard]`の位置をページ内で揃えたい要望が出てきたので注記しました。
コンポーネント定義・実装は余白を持ちつつ、利用時に位置調整をすることとしています。位置調整の方法はアプリケーション毎に異なる可能性があるためここでは触れていません。
> docs(spindle-ui): note for Breadcrumb position

- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.tsx
- packages/spindle-ui/src/Pagination/hooks/useShowItem.test.ts
- packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
Paginationのコンポーネントのアイテム数（ページ番号）描画条件を修正しました。
5件想定でしたが5件以下の処理を追加した感じです。
sliceでコネコネしようかと思ったのですが現状、if文で処理しているのでそこに追記する方法で対応しています。
合わせてstorybookも追加しております。
> fix(spindle-ui): pagination display item

- packages/spindle-ui/src/TextLink/index.ts
- packages/spindle-ui/src/index.ts
UIコンポーネント`TextLink`に関して、エントリーポイントと`export`を追加し、[Docsにある形式のモジュール`import`](https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/TextLink/TextLink.stories.mdx?plain=1#L14)が行えるようにしました🙏
> fix(spindle-ui): make enabled import TextLink from entry point

- packages/spindle-ui/src/Pagination/Pagination.css
- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.test.tsx
- packages/spindle-ui/src/Pagination/Pagination.tsx
Paginationコンポーネントの
- リンクのpadding値を修正
- showCountをShowTotalに変更
- 「次へ」「前へ」周りの改修
を対応しました。padding値とshowCountは修正の粒度が小さめだったためこのPull requestに混ぜさせてもらった形です。
値を4pxから10pxに変更しました。
デザインフィードバックの対応になります。
名前がTotalの方がわかりやすいという意見を受け変更しました。
表示仕様は下記の通りです。
今までは利用者側が表示／非表示を選択できましたが表示に関する処理はSpindle側でハンドリングするように変更しました。
| 総ページ数が100件未満の場合 | 総ページ数が100件以上の場合 |
| -------- | -------- |
| 表示     | 非表示     | 
> fix(spindle-ui): pagination prev next

- packages/spindle-ui/src/Dialog/Dialog.tsx
- packages/spindle-ui/src/Modal/AppealModal.tsx
React v18のStrict Modeを有効にしている場合に`dialog`要素の`showModal`関数が正しく機能せずエラーになる問題を修正しました
エラー文：
```
InvalidStateError: Failed to execute 'showModal' on 'HTMLDialogElement': The element already has an 'open' attribute, and therefore cannot be opened modally.
```
- Issue：https://github.com/facebook/react/issues/24399#issuecomment-1104191934
- Docs：https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors
> fix(spindle-ui): avoid running dialog showModal() twice in Strict Mode

- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.test.tsx
- packages/spindle-ui/src/Pagination/Pagination.tsx
Paginationコンポーネントの「最初へ」「最後へ」周りの改修をおこないました。
主な変更内容は下記の通りです。
- 表示条件変更
- props廃止に伴う項目削除
- props廃止に伴うstorybookとテストコード削除
今までは利用者側が表示／非表示を選択できましたが表示に関する処理はSpindle側でハンドリングするように変更しました。
変更の仕様は下記になります。
| 総ページ数が100件未満の場合 | 総ページ数が100件以上の場合 |
| -------- | -------- |
| 非表示     | 表示     | 
> fix(spindle-ui): pagination first last

- .github/workflows/release.yml
CIリリースフローの`lerna publish`がうまく動作しないことがあるため、スクリプトを以前の`npx`を使う形に戻しました
ref; https://github.com/openameba/spindle/pull/581#issuecomment-1314976132
> ci: use npx with lerna publish

- .github/workflows/release.yml
Reverts openameba/spindle#584
CIのlerna publishが落ちる問題の調査で`npx`を使用していたのを元に戻しました
> Revert "ci: use npx with lerna publish"

- packages/spindle-ui/src/Pagination/Pagination.css
- packages/spindle-ui/src/Pagination/Pagination.tsx
- packages/spindle-ui/src/Pagination/hooks/useShowItem.test.ts
- packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
PaginationコンポーネントのEllipsis（...）周りの改修をおこないました。
主な変更内容は下記の通りです。
- Ellipsisの表示条件を `数字が隣接していない場合に表示` に変更
- class名をhorizontalからellipsisに変更
- useShowItem側で定義していた処理とテストコードが不要になったため削除
```
// 数字が隣接していない場合に表示
const showEllipsis = !!displayItem[index + 1] && displayItem[index + 1] - pageNumber > 1;
{showEllipsis && (
<MenuHorizontal
aria-hidden="true"
className={`${BLOCK_NAME}-ellipsis`}
/>
)}
```
> fix(spindle-ui): show ellipsis logic

- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.tsx
PaginationコンポーネントのonPageChange周りの改修をおこないました。
主な変更内容は下記の通りです。
- onPageChangeを必須から任意に変更
- storybook
- createUrlは元々必須で他の箇所で定義されているので `create url function ` のstoryは削除
- 新たに `on page change` のstoryを追加
> fix(spindle-ui): on page change props

- .github/workflows/release.yml
[こちらのPRで更新されたREADME](https://github.com/openameba/spindle/pull/549/files#diff-94c99b905e8a1e53cf0266baf773d2becaed6017a0a1fed31275f7b02e6541e6)の通り、`spindle-ui`のビルドには事前に`spindle-hooks`のビルドをしておく必要がありました
これがリリースワークフローで漏れており、ジョブが失敗していました
リリースワークフローに`spindle-hooks`をビルドするstepを追加しました
- 以前失敗したジョブ：https://github.com/openameba/spindle/actions/runs/3468636795/jobs/5794675007#step:10:38
- 今回成功したジョブ：https://github.com/openameba/spindle/actions/runs/3562325341
> ci: fix to build spindle-hooks in release workflow

- packages/spindle-ui/src/Pagination/Pagination.css
- packages/spindle-ui/src/Pagination/Pagination.tsx
- packages/spindle-ui/src/Pagination/hooks/useShowItem.test.ts
- packages/spindle-ui/src/Pagination/hooks/useShowItem.ts
Paginationコンポーネントの
- ページ番号表示ロジック
- テストパターンの追加
をおこないました。
> fix(spindle-ui): change show item logic

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/src/Pagination/Pagination.tsx
Paginationコンポーネントのブレイクポイントによっての表示アイテム数の対応をおこないました。
端末の向きが変わった際を考慮して `orientationchange` の処理も追加しています。
また、Paginationのbundlesizeあげております。
storybookで画面幅など含めご確認いただければと！
> fix(spindle-ui): pagination breakpoint

- packages/spindle-ui/src/Dialog/Dialog.tsx
- packages/spindle-ui/src/Modal/AppealModal.tsx
AppealModalコンポーネントをEscキーで閉じた後、再度開いた際に正常に表示されない挙動を修正しました。
- `.spui-spui-AppealModal--closing`がModalを閉じた後も残ったままだった。
- 同classNameの付与を担うclosingフラグが更新されていなかった。
- dialog要素のonCloseにclosingを更新する`setClosing(false)`を渡し、Modalを閉じた後に必ず`closing === false`になるようにしました。
> fix(spindle-ui): remove closing className

- .textlintrc
- package.json
[textlintが効いていない気がしたので](https://github.com/openameba/spindle/pull/610#discussion_r1057459617)textlint周りの環境を整えました。
新たに対象となったファイルやこれまでも対象であったが手動での実行でないと検出されていなかったものが検出されるようになったため、CIは一部失敗していますが、一旦はこれでマージをして文章の修正は別のPRでするのが良いかなと思っています。
> chore: improve text linting

- .github/workflows/build-icon-from-figma.yml
- .github/workflows/build-icon.yml
- .github/workflows/build-tokens.yml
- .github/workflows/build.yml
- .github/workflows/deploy-highlightjs-styles-preview.yml
- .github/workflows/deploy-highlightjs-styles.yml
- .github/workflows/deploy-hooks-catalog.yml
- .github/workflows/deploy-hoooks-preview.yml
- .github/workflows/deploy-theme-switch.yml
- .github/workflows/deploy-ui-catalog.yml
- .github/workflows/deploy-ui-preview.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
いつからか[deploy UI catalog](https://github.com/openameba/spindle/actions/workflows/deploy-ui-catalog.yml)のワークフローが失敗する状態になっていました。
エラー内容は
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-node@v2-beta
node12サポートしてないよ。みたいな感じでした。
調べてみたらsetup-nodeのバージョンあげると解決しそう？
おもむろにv3にあげてみました。
[Release v3.0.0 · actions/setup-node](https://github.com/actions/setup-node/releases/tag/v3.0.0)
> chore: update setup node v3

- .github/workflows/visual-regression-test.yml
ボットによる Pull-request で、VRTのワークフローが動作してしまうのを動作しないように修正を試みる Pull-request です。
ワークフローに `paths` を指定しているのにもかかわらず、対象に入っていない `yarn.lock` の更新でなぜか動作してしまうのが謎なところです……
> ci: ignore VRT workflow if triggered by bot

- .github/workflows/deploy-hooks-catalog.yml
- .github/workflows/deploy-ui-catalog.yml
`lerna run` コマンドの仕様が変わったのか `--` が使えなくなったみたいで `yarn` から `npx` に乗り換えてみました。
> ci: fix ui-catalog and hooks-catalog tasks

- packages/spindle-ui/bundlesize.config.json
bundle sizeでCIコケるPRがチラホラ出現しているので、`dist/index.css`のbundle sizeを上げました 🚀
本当は、キリないので消してもいい（管理しなくて良い）のでは？と思っているものの、勇気が出ないので一旦上げました🙏🏻
> chore(spindle-ui): remove bundle size for `index.css`

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.css
- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
> fix(spindle-ui): remove underline when no href

- packages/spindle-ui/src/Modal/SemiModal.css
- packages/spindle-ui/src/Modal/SemiModal.stories.example.tsx
#494 で作成したSemiModalのデザインチェック修正PRです。
> fix(spindle-ui): semiModal styles

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
- packages/spindle-ui/src/Breadcrumb/BreadcrumbList.tsx
scrollIntoViewではなく、通常のscrollを使用して、
> コンテンツが長く、見切れた場合にはcurrent指定されているアイテムが画面内に表示されるようにスクロールします。
という仕様を満たすように修正しました。
中カテゴリがcurrentになっていた場合、横スクロールがその指定したcurrentになっていることが確認できるようにstoryを追加しました。
`scrollIntoView` を使用すると、refで指定された要素が一番上に来るようになってしまっていました。
https://user-images.githubusercontent.com/87469023/215321012-c12508ad-3c51-4085-80ee-b11afbcd3c75.mp4
https://user-images.githubusercontent.com/87469023/215321200-5027fc30-0b53-4ea5-a46e-cdaadf33267d.mp4
> fix(spindle-ui): scrollIntoView caused the breadcrumbs to come to the top of the page.

- packages/spindle-ui/src/InlineNotification/InlineNotification.css
- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.mdx
- packages/spindle-ui/src/InlineNotification/InlineNotification.tsx
InlineNotificationコンポーネントで、右側にButtonがくるパターンがあります👇
このボタンのwrap部分に対して`width: 60px`が当たっていたため、ボタンのラベルが3文字以上の場合に表示崩れしていました 👀 
よって`width` -> `min-width`に変更し、修正しました 🚀
> fix(spindle-ui): change the button width of the InlineNotification

- packages/spindle-ui/src/Modal/SemiModal.css
- packages/spindle-ui/src/Modal/SemiModal.tsx
SemiModalにて
- backdropをダブルクリックするとモーダルが閉じない
- Reactを使ったプロジェクトでIconButtonのカスタムプロパティが使えない
- iOS14にてSheetModalの位置がずれる
バグを発見したため修正しました。
> fix(spindle-ui): support for iOS14

- packages/spindle-ui/src/TextButton/TextButton.css
- packages/spindle-ui/src/TextButton/TextButton.stories.mdx
- packages/spindle-ui/src/TextLink/TextLink.css
- packages/spindle-ui/src/TextLink/TextLink.stories.mdx
TextLinkとTextButtonに対して、軽微な修正を行いました 🚀 
- TextLinkとTextButtonに、`line-height: 1.3`が足りなかったため追加 https://github.com/openameba/spindle/commit/995e06bacf24e8989be6425c0f8452672ef7160a
- stabilityを（テストも書かれているし本番運用も問題なくされているので）`unstable`から`stable`に変更 https://github.com/openameba/spindle/commit/0b2a658a47cbb81f397d10441fe9ee2fd81d7d09
- Storybookに表示されるサンプルのラベル名を、英語から日本語に変更（Ref. [StorybookのUIのラベルを日本語にする](https://github.com/openameba/spindle/issues/162)） https://github.com/openameba/spindle/commit/3a7d1b6879dcf1d47cd4b69dffffacb869d83705
> fix(spindle-ui): fix TextLink and TextButton

- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.mdx
- packages/spindle-ui/src/InlineNotification/InlineNotification.tsx
InlineNotificationコンポーネントでは、下記のようなアクセシビリティ方針を定めています
> コンポーネントからはアプリケーション内での使われ方や重要度がわからないため、aria-*属性やrole属性は付与していません。そのため、コンポーネント利用時には適宜付与して支援技術に通知してください。
にも関わらず、`InlineNotification.Frame`が`role`属性等を受け取れない実装になっていたため、修正しました 🙏🏻 
また、それに伴いドキュメントにも実装例を追加しています 📝
> fix(spindle-ui): wider acceptance of InlineNotification props

- README.md
- packages/spindle-ui/README.md
Licenseにあるリンクが404になっていたため修正をおこないました。
遷移先正しいかご確認いただきたく。
> docs: change license link

- packages/spindle-ui/src/BottomButton/BottomButton.stories.mdx
- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/ButtonGroup/ButtonGroup.stories.mdx
- packages/spindle-ui/src/Dialog/Dialog.stories.mdx
- packages/spindle-ui/src/Dialog/DialogExample.tsx
- packages/spindle-ui/src/Form/Checkbox.stories.mdx
- packages/spindle-ui/src/Form/DropDown.stories.mdx
- packages/spindle-ui/src/Form/InlineDropDown.stories.mdx
- packages/spindle-ui/src/Form/InputLabel.stories.mdx
- packages/spindle-ui/src/Form/InvalidMessage.stories.mdx
- packages/spindle-ui/src/Form/Radio.stories.mdx
- packages/spindle-ui/src/Form/TextArea.stories.mdx
- packages/spindle-ui/src/Form/TextField.stories.mdx
- packages/spindle-ui/src/Form/ToggleSwitch.stories.mdx
- packages/spindle-ui/src/LinkButton/LinkButton.stories.mdx
- packages/spindle-ui/src/Modal/AppealModal.stories.example.tsx
- packages/spindle-ui/src/Modal/AppealModal.stories.mdx
- packages/spindle-ui/src/Modal/AppealModal.tsx
- packages/spindle-ui/src/SnackBar/SnackBar.stories.mdx
- packages/spindle-ui/src/SubtleButton/SubtleButton.stories.mdx
- packages/spindle-ui/src/Toast/Toast.stories.mdx
AmebaでSpindle-uiで使用する際は基本的に日本語なので、日本語フォントのサイズ感やウェイトの具合などを確認できるようにStorybookのラベルを全て日本語化しました
また、日本語化する際は適当な文字列ではなく、Ameba内での実際の使用用途にあった日本語に変更しています
fix [StorybookのUIのラベルを日本語にする](https://github.com/openameba/spindle/issues/162)
> docs(spindle-ui): change documentation to Japanese

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/src/InlineNotification/InlineNotification.css
InlineNotification内で使われているSpindleコンポーネントのimportがInlineNotification内でされていませんでした
→ これにより、利用時にInlineNotification内部のコンポーネントまでimportしなくてはならなくなっていたので修正しました 🙏🏻
`InlineNotification with Button`
Before（利用時）
```css
@import "~@openameba/spindle-ui/Button/Button";
@import "~@openameba/spindle-ui/InlineNotification/InlineNotification";
```
After（利用時）
```css
@import "~@openameba/spindle-ui/InlineNotification/InlineNotification";
```
> fix(spindle-ui): import components related to InlineNotification

- packages/spindle-ui/src/InlineNotification/InlineNotification.css
- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.mdx
issueに記載されている通りではあるのですが、
emphasizedで定義されている `~` が原因でこの一般兄弟結合子は
> 一般兄弟結合子 (general sibling combinator, ~) は 2 個のセレクターを結びつけ、 1 つ目の要素の後に 2 つ目の要素のがあり（直後である必要はない）、かつ両者が同じ親[要素](https://developer.mozilla.org/ja/docs/Glossary/Element)の子であるすべてのパターンに一致します。
なのでstorybookのパターンが2つ並んでいるから成立しているだけで実際、単体で使おうとするとstyleが効かなくなってしまっていました。
[iconの色をつけているstyle](https://github.com/openameba/spindle/blob/4c26959df9deedac0e996962443f656f7f3617f8/packages/spindle-ui/src/InlineNotification/InlineNotification.css#L134-L137) あたりに合わせてcss修正しております。
close: #721
> fix(spindle-ui): inline notification emphasized style

- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/IconButton/IconButton.stories.mdx
- packages/spindle-ui/src/LinkButton/LinkButton.stories.mdx
主に`Lighted`variant関連のドキュメントのアップデートです 📝 
[`Lighted`variantは既に本番運用されていますが](https://github.com/openameba/spindle/pull/289)、LinkButtonのドキュメントにだけ試験中の記述が残っていたので削除しました
元々Lightedだけ試験公開していたのもあり別セクションに別れていましたが、現在は他のvariantと同等の扱いのため、セクションをマージしました
| Before | After |
| -- | -- |
| ![スクリーンショット 2023-05-29 22 36 37](https://github.com/openameba/spindle/assets/42470015/ca9e2442-77e2-4f75-83a7-66b8ea707cb8) | ![スクリーンショット 2023-05-29 22 45 29](https://github.com/openameba/spindle/assets/42470015/7a32cf26-2dbf-49b3-98e0-a69570c5e0b0) |
[SpindleのUIラベリングルール](https://spindle.ameba.design/principles/contents/ui-labeling/)に則ると、`Button（Neutral）`のドキュメントのラベルは古そうだったのでついでに修正しました
`フォローする` -> `フォロー`
fix [Lighted ButtonのStoryを修正する](https://github.com/openameba/spindle/issues/298)
> docs(spindle-ui): integrate Lighted into other variant sections

- packages/spindle-ui/src/Pagination/Pagination.css
- packages/spindle-ui/src/Pagination/PaginationItem.css
paginationの幅レイアウト処理をMedia QueryからContainer Queryに変更しました。(変更に関して @MasatoHonda 確認済みです)
Container Queryに対応していないブラウザでは非表示項目が表示されてしまいますが、致命的でないためProgressive Enhancementとして問題ないかなとは考えています。
(一応以下の形で既存の動作を担保できはしますが、ただこれまた`@supports not`に対応していないとです)
```css
@supports not (container-type: inline-size) {
...
}
```
https://ameba-spindle--pr710-feat-pagination-cq-b35rjhox.web.app/?path=/story/pagination--on-page-change-function&globals=backgrounds.grid:false あたりで幅を小さく表示し、DevToolsで確認します。
> feat(spindle-ui): pagination style with container queries

- packages/spindle-ui/bundlesize.config.json
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.css
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.stories.mdx
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.test.tsx
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.tsx
- packages/spindle-ui/src/SegmentedControl/index.ts
- packages/spindle-ui/src/index.css
- packages/spindle-ui/src/index.ts
SegmentedControlコンポーネントを作成しました。SegmentedControlは、ページ内で機能やモードを切り替える際に利用するコンポーネントで、基本機能はラジオボタンと同様です。
| Medium | Large |
|--------|--------|
| ![スクリーンショット 2023-06-21 午後2 04 04](https://github.com/openameba/spindle/assets/73621966/5e801a2d-5447-479d-865d-69a65ba18b30) | ![スクリーンショット 2023-06-21 午後2 04 09](https://github.com/openameba/spindle/assets/73621966/c0d560b9-4ea4-448a-abaa-c72bc9dcf01f) | 
https://github.com/openameba/spindle/assets/73621966/536895c8-f5f4-4153-a481-5d703d474d60
詳細な仕様に関しては、Experimental Features docsとAccessibility要件定義docsにまとめております。
> feat(spindle-ui): create SegmentedControl

- packages/spindle-tokens/config-css.js
[ameba-color-palette.css](https://github.com/openameba/ameba-color-palette.css)をspindle-tokens.cssに移行するにあたり、一発で設定変更できるように spindle-tokens.css には使われている最低限のtokenしか含まれないようにしてみます。
現時点では色はameba-color-palette.cssにお任せして、spindle-tokens.cssには新規のアニメーションだけ入れています。
ついでに全部入れてくれい！用のspindle-tokens.all.cssも作りました。
- spindle-tokens.cssをinstall (animation tokenのみ)
- ameba-color-palette.cssとspindle-tokens.cssを併用する
- spindle-tokens.cssをupdate (colorなど追加)
- ameba-color-palette.cssに記載している色をspindle-tokens.css用に変換する
- ameba-color-palette.cssを消す
> feat(spindle-tokens): include minimum tokens in token.css

- packages/spindle-tokens/.gitignore
- packages/spindle-tokens/package.json
利用するメインのCSSファイルをわかりやすく簡易的に読み込めるようにパッケージルートに配置しました。
手元でpublish dry-runするとrootでspindle-tokens.cssが配信されていることがわかります。
```
📦  @openameba/spindle-tokens@0.11.0
npm notice === Tarball Contents === 
npm notice 2.7kB   README.md                            
npm notice 0B      dist/css/spindle-tokens-animation.css
npm notice 30.4kB  dist/css/spindle-tokens.all.css      
npm notice 1.4kB   dist/css/spindle-tokens.css          
npm notice 195.4kB dist/json/spindle-tokens-flat.json   
npm notice 232.8kB dist/json/spindle-tokens.json        
npm notice 1.3kB   package.json                         
npm notice 1.4kB   spindle-tokens.css                   
npm notice 25.5kB  spindle-tokens.png 
```
> feat(spindle-tokens): publish css at package root

- packages/spindle-tokens/.stylelintrc.json
- packages/spindle-tokens/config-css.js
- packages/spindle-tokens/package.json
- yarn.lock
Animation Easing用のトークンの時に、複数回実行されると適切な値になっていなかった問題を解決しました。
例: `cubic-bezier(cubic-bezier(0, 0, 0, 1))`
また、CSSとして適切かをテストするために生成ファイルに対してstylelintを実行するようにしました。
> fix(spindle-tokens): correct invalid css property value

- packages/spindle-ui/.scaffdog/design-doc.md
- packages/spindle-ui/README.md
コンポーネントのDesign Docをscaffdogで生成できるようにしました。合わせて作業フロー(README)も更新しています。
> docs(spindle-ui): create design doc with scaffdog

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/Button/Button.tsx
ButtonコンポーネントのIcon位置が左のみ対応していたのを、左右に対応できるようにしました。
※ iconを指定した場合に初期値として左を選択させることで、破壊的変更にならないようにしています。
> feat(spindle-ui): add iconPosition to Button

- packages/spindle-ui/src/LinkButton/LinkButton.css
- packages/spindle-ui/src/LinkButton/LinkButton.stories.mdx
- packages/spindle-ui/src/LinkButton/LinkButton.tsx
LinkButtonコンポーネントのIcon位置が左のみ対応していたのを、左右に対応できるようにしました。
※ iconを指定した場合に初期値として左を選択させることで、破壊的変更にならないようにしています。
> feat(spindle-ui): add iconPosition to LinkButton

- packages/spindle-ui/src/Modal/SemiModal.css
`backgroud-color: none`がinvalidというエラーが出ていたので、transparentに変更しました。
> fix(spindle-ui): invalid SemiModal background-color type

- packages/spindle-ui/src/Modal/AppealModal.css
`backgroud-color: none`がinvalidというエラーが出ていたので、transparentに変更しました。
> fix(spindle-ui): invalid AppealModal background-color type

- .github/workflows/release.yml
> ci: improve release workflow

- packages/spindle-ui/src/Breadcrumb/design-doc.md
[Breadcrumb](https://ameba-spindle.web.app/?path=/docs/breadcrumb--breadcrumb-list) ComponentのDesign Docを移行してみました。
移行元のDesign Doc、参照したFigmaファイルはasanaのチケットに貼ります:pray:
- Variantをどう・どこに列挙するのが良いかなと悩みました 💭 （spindle-uiに多発なのでテンプレートに入っててもいい？）
- `## スクリーンショット` に追加すべきものが思い浮かばなかったので削除しましたが、なにか入れるべきだったでしょうか・・ 🤔 
- タップ領域について説明が難しかったので追加しています（後半に）
- 既に実装済みComponentのため、実装例は入れていません
> docs(spindle-ui): add Design Doc for Breadcrumb

- packages/spindle-syntax-themes/acot.config.js
- packages/spindle-syntax-themes/package.json
ref: https://developer.apple.com/forums/thread/682332
MacOS Montereyで、AirPlayの機能で5000ポートを常に使うようになってしまったために、local開発時に毎度5000ポートが利用できなくなっていました。
特段5000にこだわりがあるわけでもないので変更します。
https://github.com/openameba/spindle/pull/322#issuecomment-1670553671 も関連して発生しているようですが、なぜ #322　では ~~毎度~~ 高頻度で発生して他のPRではごく稀にしか発生しないのかははっきりしていません。
> パラレルに動いてるのでもしかしたらたまたま5000を専有するやつが競合するタイミングがあって……みたいなのなんだろうなあとは思いつつ…… by @sasaplus1 
Montereyの人：
1. システム環境設定→共有→左側の「AirPlayレシーバー」にチェックが入っていることを確認
2. `$ yarn test` 実行して全て成功すること
3. Workflowのtestが成功していることを確認
それ以外の人：なんだろう 🤔 
1. `$ yarn test` 実行して全て成功すること
2. Workflowのtestが成功していることを確認
・・かなw
> build(spindle-syntax-themes): change port to 5001

- packages/spindle-ui/src/SegmentedControl/SegmentedControl.test.tsx
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.tsx
`SegmentedControl` を利用する際に渡している `selectedId` が利用元で更新された際に、 `SegmentedControl`内で保持している `selectedId` が更新されていなかったので、修正しました。
`userSelectedId`(渡ってきた`selectedId`)が更新された際の処理を追加しました。
テストケースをアップデートしたので不備が無いか確認をお願いします。
> fix(spindle-ui): SegmentedControlに渡っている値が更新された際の処理を追加

- .github/workflows/visual-regression-test.yml
- github.actorがボットだった場合の処理を削除しました
- パスのフィルターにGitHub Actions標準の構文を使うようにしました
- typesやbranchesやpathsなど、複数の条件を指定すると意図に反するような動きをするが、単体で使用するのなら問題ないと思ったため
> ci: fix VRT condition

- .github/workflows/release.yml
https://github.com/openameba/ameba-color-palette.css/pull/93#discussion_r1277009262 により追加しました。
Error: https://github.com/openameba/spindle/actions/runs/6007814783/job/16294523111
> ci: add permissions to releasing job

- packages/spindle-ui/package.json
[準備が足りていなかった](https://docs.npmjs.com/generating-provenance-statements#:~:text=Ensure%20your%20package.json%20is%20configured%20with%20a%20public%20repository%20that%20matches%20where%20you%20are%20publishing%20with%20provenance%20from.)ようなので、`repository` を追加しました。ひとまずリリース対象のspindle-uiに入れてみます。
ref: https://github.com/openameba/ameba-color-palette.css/blob/0d2ec79028abb272b8a8249f49dadb52998c4f09/package.json#L9-L12
> Failed to validate repository information: package.json: “repository.url” is “undefined”, expected to match “https://github.com/openameba/spindle” from provenance https://github.com/openameba/spindle/actions/runs/6007998381/job/16294989755
> ci(spindle-ui): add repository url

- .github/workflows/build-icon-from-figma.yml
- .github/workflows/build-icon.yml
- .github/workflows/build-tokens.yml
別件で[peter-evans/create-pull-requesを眺めていて](https://github.com/peter-evans/create-pull-request#:~:text=(permissions%20contents%3A%20write%20and%20pull%2Drequests%3A%20write))、permissions設定で[諦めかけていたPR Author指定](https://github.com/openameba/spindle/pull/797#issuecomment-1709344463)できるのでは？を試してみました。
できていそうな感じがします。
https://github.com/openameba/spindle/pull/802
> ci: set permissions to create PR

- packages/spindle-ui/src/TextButton/TextButton.css
- packages/spindle-ui/src/TextButton/TextButton.stories.mdx
[TextButtonのdisabledスタイル](https://spindle.ameba.design/components/button/#%E7%8A%B6%E6%85%8B)がなかったので適用しました。
underlineは一貫して「なし」で @MasatoHonda と確認しました。
> fix(spindle-ui): add TextButton disabled style

- packages/spindle-ui/src/Pagination/Pagination.stories.mdx
- packages/spindle-ui/src/Pagination/Pagination.test.tsx
- packages/spindle-ui/src/Pagination/Pagination.tsx
- packages/spindle-ui/src/Pagination/PaginationItem.tsx
- packages/spindle-ui/src/Pagination/helpers/getLinkRelAttribute.test.ts
- packages/spindle-ui/src/Pagination/helpers/getLinkRelAttribute.ts
下記Design Docsに従い、Paginationの`rel="nofollow"`に関する修正を行いました。
close: https://github.com/openameba/spindle/issues/826
指定必須のpropsを追加したので、[BREAKING CHANGE](https://github.com/openameba/spindle/commit/4a13ef3207069cae314977d21c7d53603c947d66)です。
> feat(spindle-ui): add link follow type in pagination

- packages/spindle-ui/src/BottomButton/design-doc.md
[BottomButton](https://ameba-spindle.web.app/?path=/docs/bottombutton--fixed-position) ComponentのDesign Docを移行しました。
移行元のリンクはasanaに記載しています。
> docs(spindle-ui): add Design Doc for BottomButton

- packages/spindle-ui/src/Form/DropDown.css
DropDownでstyle崩れ（safariのみ）が発生していたため修正しました。
原因としては `listitem` を使うことでsafariの場合、幅を担保するための`padding`が受け付けなくなっていました。
なので全部リセットする `none` に変更した次第です。
すでにリリース済みのコンポーネントのためできるだけ早いとありがたいです。
> fix(spindle-ui): drop down appearance style

- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.mdx
- packages/spindle-ui/src/InlineNotification/design-doc.md
InlineNotificationコンポーネントのDesignDocsを移行しました
🔗 [Storybook - InlineNotification](https://ameba-spindle.web.app/?path=/docs/inlinenotification--information)
🔗 [DesignDocsのプレビュー](https://github.com/openameba/spindle/blob/docs/add-inline-notification-docs/packages/spindle-ui/src/InlineNotification/design-doc.md)
- レビュー完了希望日: 10/27（金）
> docs(spindle-ui): add DesignDocs for InlineNotification 

- packages/spindle-hooks/tsconfig.json
- packages/spindle-ui/tsconfig.json
https://github.com/openameba/spindle/pull/844#issuecomment-1826990725 のtestが落ちるのを修正します。
おそらくjest-domを[v6系](https://github.com/testing-library/jest-dom/releases/tag/v6.0.0)に上げてから発生しているのではと想像しています。（v6.0.0でtypes周りが大きく変わっています）
v6以前は `@types/testing-library__jest-dom"` を使っていたようですが、v6から[jest-dom内で自前の型定義ファイルを作成するようになった](https://github.com/testing-library/jest-dom/pull/511/files#diff-baec3cdaf936322986fb071fbeed16b784ac14926409ebba5469ce6d6ce054c4)みたいです。
> testing-library/jest-domは独自の型定義を提供するので、@types/testing-library__jest-domをインストールする必要はありません！
https://www.npmjs.com/package/@types/testing-library__jest-dom （翻訳）
とのことなので `@types/testing-library__jest-dom` ではなく `testing-library/jest-dom` をコンパイルする必要がありそうです。
[tsconfigのtypesはデフォルトで `@types`パッケージをコンパイルします](https://www.typescriptlang.org/tsconfig#types)が、 …
> test(spindle-ui): fix import jest-dom types

- .github/workflows/lint-commit-message.yml
https://github.com/openameba/spindle/pull/858#issuecomment-1845117345 のように人間がコミットメッセージについてレビューする必要がある
`commitlint`がインストールされるよう`package.json`に記述されているのでそれを利用してCIで検査させる
CIにある程度機械的にコミットメッセージを検査させ、人間が楽をする
> ci: lint commit messages

- .github/workflows/lint-commit-message.yml
https://github.com/openameba/spindle/actions/runs/7175709702/job/19539460009 等、タイムアウトしてしまうことがあったので改善しました。
修正内容としては以下の2点です。
- そもそもキャッシュの展開がうまくいっておらずモジュールを新規ダウンロードしてしまっていたこと
- タイムアウトの指定が短いので延長しました
> ci: fix restore cache

- .github/workflows/deploy-highlightjs-styles-preview.yml
- .github/workflows/deploy-highlightjs-styles.yml
- .github/workflows/deploy-hooks-catalog.yml
- .github/workflows/deploy-hoooks-preview.yml
- .github/workflows/deploy-theme-switch-preview.yml
- .github/workflows/deploy-theme-switch.yml
- .github/workflows/deploy-ui-catalog.yml
- .github/workflows/deploy-ui-preview.yml
[Firebase HostingにデプロイできずPRが取り込めない](https://github.com/openameba/spindle/pull/858#issuecomment-1849246603)ので、取り急ぎデプロイできるようにしました。
本質的にはnodeバージョンを上げるべきですが、変更範囲がFirebase関連以外にもあり、対応にやや時間を要するため[firebase-toolsのバージョン](https://github.com/firebase/firebase-tools/releases)を落として現状のnodeで動作するようにしています。
成功workflow: https://github.com/openameba/spindle/actions/runs/7189444688/job/19580966571
> ci: set firebase-tools version to deploy

- packages/spindle-ui/src/NavigationTab/UnderlineTab/design-doc.md
NavigationTab/UnderlineTabのDesign docsを記載しました。
Figmaへのリンクはasanaのチケットに貼っています。
詰め切れてない箇所はあるのですが、一旦大枠の設計方針をレビューいただければと思っています:bow:
コメントにて補足を記載していきます。
> docs(spindle-ui): add Design Doc for UnderlineTab

- packages/spindle-ui/src/DropdownMenu/DropdownMenu.test.tsx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.tsx
dropdown menu 利用ページでescキー押下時に、focusがdropdown menu 利用箇所に当たってしまう
- dropdown menu が開いているときのみ、windowにEventListenerを追加するように変更した
- 類似箇所で dropdown menuが開いているときのみ、EventListenerが必要な箇所で同様の変更をおこなった
- 開いていないときにEventListenerが無駄に作成されないようにするため（メモリ消費の効率化）
- Dropdown Menu利用箇所で、Dropdown Menuを開いていない状態で esc キーを押下しても何も起こらないこと
- Dropdown Menuを開いた状態で esc キーを押下して Dropdown Menuが閉じられること
- Dropdown Menuを開いた状態で Dropdown Menu以外の要素をクリックしたとき Dropdown Menuが閉じられること
- Dropdown Menuが閉じるときにFadeアニメーションがついていること
> fix: esc handler should be attached only when the drop menu is opened.

- lerna.json
Versioning時のコミットメッセージをcommitlintで通るように変更しました。`useWorkspaces: true` でも解決する気はしますが、ここのメッセージにこだわりはないので変更しました。
> WARN EWORKSPACES To fix this and have Lerna use workspaces to resolve packages, set `useWorkspaces: true` in lerna.json.
https://github.com/openameba/spindle/actions/runs/7204624689/job/19626362168?pr=868
ref: https://github.com/openameba/spindle/pull/868#issuecomment-1855393308
> chore: update versioning commit message

- .github/workflows/build-icon-from-figma.yml
- .github/workflows/build-icon.yml
- .github/workflows/build-tokens.yml
- .github/workflows/build.yml
- .github/workflows/deploy-highlightjs-styles-preview.yml
- .github/workflows/deploy-highlightjs-styles.yml
- .github/workflows/deploy-hooks-catalog.yml
- .github/workflows/deploy-hoooks-preview.yml
- .github/workflows/deploy-theme-switch-preview.yml
- .github/workflows/deploy-theme-switch.yml
- .github/workflows/deploy-ui-catalog.yml
- .github/workflows/deploy-ui-preview.yml
- .github/workflows/lint-commit-message.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/visual-regression-test.yml
- packages/spindle-hooks/package.json
- packages/spindle-ui/bundlesize.config.json
[firebase tools v13.0.0](https://github.com/firebase/firebase-tools/releases/tag/v13.0.0)以降からNode.js v16以下をサポートしなくなりました。
現状は、firebase toolsのバージョンを下げて対応(https://github.com/openameba/spindle/pull/866) していますが、本来はNode.js側を上げるべきなのでこのPRでそちらの対応を行いました！
> feat: node to version 18

- packages/spindle-hooks/README.md
- packages/spindle-ui/README.md
Browser Supportの記述が更新されていなかったので対応しました (本当はv1の時にしたかった)。
> AmebaとしてはIE11の動作保証を切っており、UIの崩れ等は保証していないのでIEでレイアウト崩れてもいいかな？はYesになりますね〜。
https://helps.ameba.jp/faq/others/5510/top_08.html
https://helps.ameba.jp/faq/ameba/0215/post_1111.html
by :pagu:
> docs(spindle-hooks,spindle-ui): browser support

- .github/workflows/visual-regression-test.yml
I suspect this is the explanation for https://github.com/openameba/spindle/pull/645#issuecomment-1396540064
Note that this PR should be considered very scary. What you had previously was dangerous in that it was a workflow with full write permissions that could run from a PR (like this one), but because of the logic errors being fixed here, it didn't do everything that it was trying to do (namely conditionally run for PRs from forks).
With the changes here, you will be *running* the untrustworthy code (or in places the merge of the untrustworthy code).
Thus, if you are going to do this, you should make sure that:
1. `secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON` can *only* be used to write to `secrets.GCS_BUCKET_NAME_REG_SUIT` (probably without being able to delete existing content)
2. …
> Visual regression test with permissions

- examples/css-modules/src/main.tsx
- examples/preact/src/main.tsx
- examples/styled-components/src/main.tsx
Task [build design tokens via webhook](https://github.com/openameba/spindle/actions/workflows/build-tokens.yml) を実行したいですが、エラー(ReactDOM.render is no longer supported in React 18) が出るので対応しました。
※ example用途のディレクトリなのでソースコード変更しましたが、動作確認は~あんまり~してません
ref: https://github.com/openameba/spindle/actions/runs/7326304838/job/19951823465
> chore: updates to React client rendering API

- .github/workflows/deploy-highlightjs-styles-preview.yml
- .github/workflows/deploy-hoooks-preview.yml
- .github/workflows/deploy-theme-switch-preview.yml
- .github/workflows/deploy-ui-preview.yml
Pull Request上でFirebase HostingのPreviewをする上で必要なpermissionsを設定しました。
検証は以下のブランチ (PR) でしています。
https://github.com/openameba/spindle/pull/885
- [pull-requestsはwriteがないとコメントできなかった](https://github.com/openameba/spindle/actions/runs/7328010807/job/19955656870)
- [contentsのreadがないとコメント内容が空だった](https://github.com/openameba/spindle/actions/runs/7328054607/job/19955765922)
> ci: set permissions for firebase hosting preview

- .renovaterc.json
renovateが作るPRのコミットスコープをdepsから何もない`chore:`となるようにしました
- ref: https://github.com/openameba/spindle/pull/857#issuecomment-1869477922
- ref: https://docs.renovatebot.com/semantic-commits/#changing-the-semantic-commit-scope
> chore: disable commit scope for renovate

- packages/spindle-ui/src/Dialog/Dialog.stories.mdx
https://ameba-spindle.web.app/?path=/docs/dialog--button-column-with-subtle-button ← のexampleで、`SubtleButton`で閉じられるべきところが`Button`になっていたので修正しました！
| code  | Stroybook |
| ------------- | ------------- |
| https://github.com/openameba/spindle/blob/75b50c6656183551fc6aab28c22ff09fdb6d6e4f/packages/spindle-ui/src/Dialog/DialogExample.tsx#L118  | https://github.com/openameba/spindle/blob/75b50c6656183551fc6aab28c22ff09fdb6d6e4f/packages/spindle-ui/src/Dialog/Dialog.stories.mdx#L216-L218  |
> docs(spindle-ui): fix to close with SubtleButton

- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
Buttonの高さがFigmaと異なっていたので、修正しました。
元々「/* Button variants have different vertical padding to normalize height */」とコメントがあったのでvariantごとに設定される前提のようでしたが、現状のFigmaではsizeごとで良さそうなのでそちらに変更しています。~また、min-heightが設定されており、中央位置配置はFlexboxで行なっているので上下のpaddingは0px指定に変更しました。~
また、[サイズごとに上下余白が指定されている](https://www.figma.com/file/vVkCe93sDd0NK6JP5DmQOt/Spindle-UI-(Community)?type=design&node-id=367-44426&mode=design&t=7XmP83ZLvJLtifw1-0)ので揃えました。
※ Smallボタンは6pxに変更予定です by @MasatoHonda 
Figma: https://www.figma.com/file/vVkCe93sDd0NK6JP5DmQOt/Spindle-UI-(Community)?node-id=367%3A44210&mode=dev
fix #368
> fix(spindle-ui): change padding to correct Button height

- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.css
- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.stories.mdx
- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.test.tsx
- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.tsx
- packages/spindle-ui/src/NavigationTab/UnderlineTab/design-doc.md
- packages/spindle-ui/src/NavigationTab/index.css
- packages/spindle-ui/src/NavigationTab/index.ts
- packages/spindle-ui/src/index.css
[DesignDocs](https://github.com/openameba/spindle/blob/main/packages/spindle-ui/src/NavigationTab/UnderlineTab/design-doc.md#%E4%BD%BF%E7%94%A8%E4%BE%8B)に沿って、`NavigationTab/UnderlineTab`コンポーネントを実装しました
設計（DesignDocs）段階では、`UnderlineTab`の各項目がリンクの場合とボタンの場合の両方を考慮していました
...が、`UnderlineTab`の利用予定画面では現状ボタンのパターンしか存在せず（またリンク要件が存在するわけでもないため）、設計者 @tatz-ibz と話し合いの上現時点ではボタンのパターンのみ考慮にすることにしました
※ 今後リンク要件が出てくる可能性はあるため、DesignDocsからは削っていません
---
その他細かい変更箇所については、`design-doc.md`の差分にコメントする形で言及しています 📝 
2/5（月）
Figma等の関連リンクは、AccessibilityチームのAsanaの概要欄に貼ってあります 📝 
また、デザイナーさんとやりとりした細かなデザイン仕様についてはFigma上にコメントしています 📝
> feat(spindle-ui): add `NavigationTab/UnderlineTab` component

- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.stories.mdx
- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.tsx
https://github.com/openameba/spindle/pull/909 で追加した`NavigationTab/UnderlineTab` にて、一部修正箇所を見つけたので対応しました
- ドキュメントのIDが一意になるように修正： https://github.com/openameba/spindle/pull/925/commits/2f392feb9d0154613aa3eb8f1629d7fd612c6b9f
- マークアップを一部変更： https://github.com/openameba/spindle/pull/925/commits/ec66c4f33a05403830564fdb55bcd0cff2d9cb0e
- 実装例（HTML）が古い実装のままになっていたので修正：https://github.com/openameba/spindle/pull/925/commits/7c3ca85304f92b2237da3f50e789648066b9fc77
2/8（木）
`Hide whitespace`を ✅ してcommitベースで見るのが追いやすいかもです 🙏🏻
> fix(spindle-ui): fix `NavigationTab/UnderlineTab` component

- packages/spindle-ui/src/SnackBar/SnackBar.tsx
> fix(spindle-ui): Fix snackbar/textlink type

- packages/spindle-ui/src/Form/Radio.css
- packages/spindle-ui/src/Form/Radio.stories.mdx
spindle-uiのRadioボタンを使っている際に、文言の長さ＋端末幅、あるいは画面・テキストサイズの拡大率によってはラジオボタンが縦に潰れて表示されてしまうため修正しました。
before|after
---|---
選択肢のラベルが長い時にラジオボタンが縦に潰れて表示されている|長い時にもラジオボタンは正円で表示されている
基本的にこのレベルの長文を表示することは想定していませんが、[1.4.4 テキストサイズを拡大縮小できる](https://a11y-guidelines.ameba.design/1/4/4/)ことでアクセシビリティを高められるので、長文に適応できることでテキストサイズの拡大やリフローに耐えうるので修正すべきと判断しました。
関連しそうなアクセシビリティのガイドライン：
- [1.4.4 テキストサイズを拡大縮小できる](https://a11y-guidelines.ameba.design/1/4/4/)
- [1.4.10 リフローできる](https://a11y-guidelines.ameba.design/1/4/10/)
> fix(spindle-ui): 選択肢が長い時にラジオボタンが潰れて見える

- packages/spindle-ui/package.json
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.test.tsx
- packages/spindle-ui/src/Pagination/hooks/useItemPageNumber.test.ts
- packages/spindle-ui/src/Pagination/hooks/useShowItem.test.ts
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.test.tsx
- packages/spindle-ui/src/StackNotificationManager/hooks.test.tsx
- packages/spindle-ui/src/StackNotificationManager/hooks.ts
- yarn.lock
_(後続で使いたいので)_ Spindle UIのReactをv18にしました。
現状でも互換性がありそのまま使えるので、ライブラリのコード自体は変えず以下の点を変更しました:
- peerDependenciesと dependencies のバージョン更新  https://github.com/openameba/spindle/commit/65e6f146cac315133b53a73453c29d18983ef75b
- テストコードのアップデート
- update @testing-library/react b84e9ca8be19dc4ed0b0fba7b1cd31357cebfe9c
- @testing-library/react-hooks to @testing-library/react ref: https://github.com/testing-library/react-hooks-testing-library?tab=readme-ov-file#a-note-about-react-18-support 4038556056a8b367e4434203dc3a9a24c6d30581
- テストコードの修正 4038556056a8b367e4434203dc3a9a24c6d30581
- 利用しないライブラリの削除 1df6a97d5ba9eaa50de3a4fecc94f1efb99c8f8f
close #1023
> chore(spindle-ui): update React to 18

- .github/workflows/dependabot-auto-merge.yml
細かく取り込めていいんですが、_ぽちぽち大変_なのでauto mergeのワークフロー作りました。
マージ条件(minor, patch)以外はほぼコピペです。
ref: https://docs.github.com/ja/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
> ci: auto merge dependabot

- packages/spindle-ui/src/InlineNotification/InlineNotification.figma.tsx
> chore(spindle-ui): change prop names in InlineNotification.figma.tsx

- packages/spindle-hooks/package.json
- packages/spindle-tokens/package.json
- packages/spindle-ui/package.json
- yarn.lock
Bumps [jest](https://github.com/jestjs/jest/tree/HEAD/packages/jest) and [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/jest). These dependencies needed to be updated together.
Updates `jest` from 29.0.0 to 29.7.0
- [Release notes](https://github.com/jestjs/jest/releases)
- [Changelog](https://github.com/jestjs/jest/blob/main/CHANGELOG.md)
- [Commits](https://github.com/jestjs/jest/commits/v29.7.0/packages/jest)
Updates `@types/jest` from 27.0.1 to 29.5.13
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/jest)
---
updated-dependencies:
- dependency-name: jest dependency-type: direct:development update-type: version-update:semver-minor
- …
> chore: bump jest and @types/jest

- .eslintrc.json
- .github/workflows/build.yml
- bin/outputExtensionReplace.js
- bin/outputExtensionReplace.test.js
- bin/outputExtensionReplace.ts
- package.json
- yarn.lock
packageが出力する成果物のmjsがspindle内部のモジュールを参照している時に、拡張子を省略しない対応を加えました。
ESMで開発しているプロジェクトでBreadcrumbListの利用を試みた所 `node_modules/@openameba/spindle-ui/Breadcrumb/BreadcrumbList.mjs` にある `import ChevronRightBold from '../Icon/ChevronRightBold';` が解決出来ないという問題が発生しました。
ESMでは相対参照において拡張子を省略しないことが期待されるので出力後のmjs内に存在する、相対参照を拡張子が省略されていない形へ置き換える対応を加えました。
dist配下に出力される成果物の内容の
```mjs
export { BreadcrumbItem, BreadcrumbList } from './Breadcrumb';
export { Button } from './Button';
import { ButtonGroup as Group } from '../ButtonGroup';
import ChevronRightBold from '../Icon/ChevronRightBold';
import ChevronRight from '../Icon/ChevronRight';
```
のようなimport/exportの参照が
```mjs
export { BreadcrumbItem, BreadcrumbList } from './Breadcrumb/index.mjs';
export { Button } from './Button/index.mjs';
import { ButtonGroup as …
```
> build: 出力されたmjsの内部参照で拡張子を指定するようにアップデート

- packages/spindle-ui/src/Button/Button.stories.mdx
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.stories.example.tsx
- packages/spindle-ui/src/Form/Checkbox.tsx
- packages/spindle-ui/src/Form/DropDown.tsx
- packages/spindle-ui/src/Form/InlineDropDown.tsx
- packages/spindle-ui/src/Form/InvalidMessage.tsx
- packages/spindle-ui/src/Form/Radio.tsx
- packages/spindle-ui/src/IconButton/IconButton.stories.mdx
- packages/spindle-ui/src/InlineNotification/InlineNotification.figma.tsx
- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.example.tsx
- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.mdx
- packages/spindle-ui/src/LinkButton/LinkButton.stories.mdx
- packages/spindle-ui/src/List/MoreLink.tsx
- packages/spindle-ui/src/Modal/AppealModal.tsx
- packages/spindle-ui/src/Modal/SemiModal.tsx
- packages/spindle-ui/src/SnackBar/SnackBar.figma.tsx
- packages/spindle-ui/src/SnackBar/SnackBar.stories.mdx
- packages/spindle-ui/src/SnackBar/SnackBar.tsx
- packages/spindle-ui/src/StackNotificationManager/StackNotificationManager.stories.example.tsx
- packages/spindle-ui/src/TextButton/TextButton.stories.mdx
- packages/spindle-ui/src/TextLink/TextLink.stories.mdx
- packages/spindle-ui/src/Toast/Toast.stories.mdx
- packages/spindle-ui/src/Toast/Toast.tsx
- packages/spindle-ui/src/icons.figma.tsx
close https://github.com/openameba/spindle/issues/1174
ast-grepを用いて機械的に実行しました
```yml
id: fix-icon-imports
message: found target icon import
severity: info # error, warning, info, hint
language: Tsx
rule:
pattern: import {$$$IDENTS} from '$ICON'
regex: Icon'|Icon/
rewriters:
- id: rewrite-identifier
rule:
pattern: $IDENT
kind: identifier
fix: import $IDENT from '$ICON/$IDENT';
transform:
IMPORTS:
rewrite:
rewriters: [rewrite-identifier]
source: $$$IDENTS
joinBy: "\n"
fix: $IMPORTS
```
> refactor(spindle-ui): replace icon index imports with direct imports

- packages/spindle-theme-switch/tsconfig.json
`deploy theme switch preview` のActionがコケていたため、そちらの対応を行いました。
#1108 でActionがコケているにもかかわらずオートマージされた差分が原因でコケていたため、こちらの対応を行いました。
package.jsonのtypesの指定がexportsの指定に置き換わったため、型を見つけられなくなった。
https://github.com/GoogleChromeLabs/dark-mode-toggle/commit/6ecfb2a5c4db2942f58af7752ea7f242c33f0ba6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R10-R17
`moduleResolution` を `node16` へ変更しました。
https://www.typescriptlang.org/tsconfig/#moduleResolution
に記載されている
> 'node16' or 'nodenext' for modern versions of Node.js. Node.js v12 and later supports both ECMAScript imports and CommonJS require, which resolve using different algorithms. These moduleResolution values, when combined with the corresponding [module](https://www.typescriptlang.org/tsconfig/#module) values, picks the right algorithm …
> build(spindle-theme-switch): moduleResolutionの設定値をnode16に変更

- packages/spindle-ui/src/Form/ToggleSwitch.tsx
- packages/spindle-ui/src/types/react.d.ts
Safariで\<input type="checkbox" switch\>が対応されたので、switch属性を追加しました。スタイルはSpindle定義のものを使いたいのでそれ以外の変更はないですが、スクリーンショットの通りroleがswitchになるのでより正確になるかなと思います。属性追加に際して互換性が担保されているためサポートしていないブラウザでは何も起こらないはずです。
サポートブラウザが広がりしだいスタイルも対応できたらと思います。
ref: [Safari 17.4 supports \<input type="checkbox" switch\>](https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes#New-Features:~:text=checkbox%22%20switch%3E.%20(-,119378678,-))
Preview: https://ameba-spindle--pr1114-feat-input-switch-gsn3fmis.web.app/?path=/story/form-toggleswitch--toggle-switch
> feat(spindle-ui): add switch attribute to ToggleSwitch

- .github/workflows/build-icon-from-figma.yml
Figmaからのアイコン生成時にenvの指定が漏れていたので対応しました。
(@MasatoHonda の報告により発覚しました)
error: https://github.com/openameba/spindle/actions/runs/13126344361/job/36623323870
理想的な設定な方: 
https://github.com/openameba/spindle/blob/a43eb5879733e3b266b64cd8b54a8ca62e89b7a3/.github/workflows/build-icon.yml#L32-L34
> ci: add env to export icons from Figma

- .github/workflows/build-icon-from-figma.yml
`fix` が必要でした。
ref: https://github.com/openameba/spindle/blob/e1c8b0e46214f57e24bb535b5e76335a3a5cf15c/.github/workflows/build-icon.yml#L42C16-L42C19
error: https://github.com/openameba/spindle/actions/runs/13128281813/job/36628594815
> ci: fix format error in building icon workflow

- packages/spindle-hooks/package.json
spindle-hooksをpublishすると `dist/` が含まれないまま公開されてしまう。
dist/を明示的に含めるためにfilesを指定しました。
`$ npm pack` で含まれることを確認しました
> chore(spindle-hooks): spindle-hooksのdist/をpackageに含める

- packages/spindle-tokens/.stylelintrc.json
- packages/spindle-tokens/config.js
- packages/spindle-tokens/tokens/font.tokens.json
[Spindleサイト](https://spindle.ameba.design/styles/typography/ui/)で更新した font-family のデザイントークンを反映しました。
ref: https://tr.designtokens.org/format/#font-family
CSSは以下のように書き出されます。
<details>
<summary>spindle-tokens-font.css</summary>
```css
/**
* Do not edit directly, this file was auto-generated.
*/
:root {
--font-font-family-blog-body: -apple-system, BlinkMacSystemFont, sans-serif;
--font-font-family-basic-version-2: 'Helvetica Neue', Helvetica, Arial, 'Segoe UI', 'Hiragino Sans', 'ヒラギノ角ゴ ProN', 'Hiragino Kaku Gothic ProN', 'Hiragino Kaku Gothic Pro', メイリオ, Meiryo, 'Yu Gothic Medium', sans-seri;
--font-font-family-basic-version-1: Meiryo, 'Yu Gothic Medium', system-ui, -apple-system, BlinkMacSystemFont, sans-serif;
}
```
</details>
Chromeで確認したところ、指定されているようでした。
> feat(spindle-tokens): create font tokens

- packages/spindle-hooks/package.json
- packages/spindle-ui/package.json
(とある案件で使いたいため) 利用できるReactのバージョンに19を追加しました。問題出たら、:sugu: 対応します。
> chore(spindle-ui,spindle-hooks): set React 19 to peerDependencies

- .github/workflows/test.yml
前回 #1207 で対応した問題が再発していたので、根本解決を試みました。
1. cacheから復元した際にブラウザが存在するかの確認
- https://github.com/openameba/spindle/actions/runs/13298300334/job/37134953641#step:5:7
- 存在は確認出来た
2. test実行時に `PUPPETEER_EXECUTABLE_PATH` へ `/usr/bin/google-chrome-stable` を明示的に指定
- ブラウザは入っているが、参照先が違っていそうだったので、明示的に指定しました
> chore: test時にPUPPETEER_EXECUTABLE_PATHを設定

- packages/spindle-tokens/config.js
- packages/spindle-tokens/tokens/shadow.tokens.json
shadowのtokenを `@openameba/spindle-tokens` から利用できるようにしました。
[定義ファイル](https://github.com/openameba/spindle/tree/main/packages/spindle-tokens/tokens/shadow)を元に以下のようなCSSが生成されます。アプリケーションでは [box-shadow](https://developer.mozilla.org/ja/docs/Web/CSS/box-shadow) として `--box-shadow-lv*` or [drop-shadow](https://developer.mozilla.org/ja/docs/Web/CSS/filter-function/drop-shadow) `--drop-shadow-lv*` を使います。
<details>
<summary>spindle-tokens-shadow.css</summary>
```css
:root {
--box-shadow-lv6-weak: 0 11px 28px 0 #08121a0f;
--box-shadow-lv6-strong: 0 11px 28px 0 #08121a3d;
--box-shadow-lv6-normal: 0 11px 28px 0 #08121a1f;
--box-shadow-lv4-weak: 0 4.75px 14.25px 0 #08121a0f;
--box-shadow-lv4-strong: 0 4.75px 14.25px 0 #08121a3d;
--box-shadow-lv4-normal: 0 4.75px 14.25px 0 #08121a1f;
--box-shadow-lv2-weak: …
```
> feat(spindle-tokens): create shadow tokens

- packages/spindle-hooks/package.json
- packages/spindle-ui/package.json
#1178 で内部参照の拡張子を置き換える処理を追加しましたが、リリース時に実行されるのは個別パッケージのbuildなので、リリース時に置き換えが実行されていなかったのを修正しました。
少々不格好なのでリリースフロー自体を見直す等したいのですが、ひとまず意図したとおりに配信されるのを優先し、今回の対応を加えました。
spindle-ui,spindle-hooksの階層で `yarn build` を実行し、distに出力されたものの置き換えが完了しているのかを確認する。
> build(spindle-ui,spindle-hooks): 個別パッケージのbuild時にもextensionReplaceが実行されるように修正

- packages/spindle-ui/src/Form/DropDown.css
> fix(spindle-ui): set DropDown background color

- packages/spindle-ui/src/Form/DropDown.css
- packages/spindle-ui/src/Form/DropDown.stories.mdx
- packages/spindle-ui/src/Form/TextArea.css
- packages/spindle-ui/src/Form/TextArea.stories.mdx
- packages/spindle-ui/src/Form/TextField.css
- packages/spindle-ui/src/Form/TextField.stories.mdx
現在 `hasError` で意図的にエラーを指定できるコンポーネントに [user-invalid](https://developer.mozilla.org/ja/docs/Web/CSS/:user-invalid) のタイミングで自動的にエラー表示になるように追加しました。
JSライブラリで状態を管理したい場合は主に前者、formで管理したい場合は主に後者を利用するイメージです。
`:user-invalid` 時は強制的にエラー表示にしてしまって問題ないと考えていますが、懸念になりそうなことがあったら教えてください！
> feat(spindle-ui): :user-invalid for input errors

- packages/spindle-ui/src/ButtonSwitch/design-doc.md
新規コンポーネント`ButtonSwitch`のDesign Docです。
> docs(spindle-ui): add design doc for buttonSwitch

- examples/css-modules/package.json
- examples/css-modules/yarn.lock
- examples/postcss/package.json
- examples/postcss/yarn.lock
- examples/preact/package.json
- examples/preact/yarn.lock
- examples/styled-components/package.json
- examples/styled-components/yarn.lock
- packages/spindle-ui/package.json
- yarn.lock
spindle-uiとexamples以下の各パッケージが依存しているameba-color-palette.cssのバージョンを、4.14.0に上げました。
ただし、examples/sassについてはnode-sassがNode.js v13しか対応しておらずアップグレードできなかったため、一旦除外しました。
> chore: upgrade ameba-color-palette.css

- packages/spindle-mcp-server/dist/design-token.d.ts
- packages/spindle-mcp-server/dist/design-token.js
- packages/spindle-mcp-server/src/design-token.test.ts
- packages/spindle-mcp-server/src/design-token.ts
CSSトークンがうまく読み込まれない時があるので、ドキュメントを追加しました。
> feat(spindle-mcp-server): add doc for css token installation

- packages/spindle-ui/src/Breadcrumb/Breadcrumb.stories.mdx
`BreadcrumbList` を利用する際に、`BreadcrumbItem` を使うことがデフォルトなので、一緒に import するサンプルにしました。
> docs(spindle-ui): import BreadcrumbItem with BreadcrumbList

- packages/spindle-mcp-server/dist/accessibility.d.ts
- packages/spindle-mcp-server/dist/accessibility.js
- packages/spindle-mcp-server/dist/index.js
- packages/spindle-mcp-server/src/accessibility.ts
- packages/spindle-mcp-server/src/index.ts
調査の結果、実装のDesign Docを作成する際に有用そうなので、アクセシビリティのチェックリストを取得できるようにしておきます。
※ 現状そのままMCPサーバーを使えるようにするため、成果物 (`dist/`)もgit管理に含めています。
※ チェックリストは今後ファイル管理するかもしれません
> docs(spindle-mcp-server): a11y checklist

- packages/spindle-tokens/scripts/color.ts
Figmaファイルの移行(整理)に対応できていなかったので、更新しました。書き出しは別で行います。
> fix(spindle-tokens): correct figma id for colors

- packages/spindle-tokens/package.json
- yarn.lock
`build design tokens via webhook ` の処理で
https://github.com/openameba/spindle/actions/runs/15013285054/job/42185794204
```
yarn run v1.22.22
$ /home/runner/work/spindle/spindle/node_modules/.bin/lerna run --scope @openameba/spindle-tokens export
lerna notice cli v8.1.8
lerna info versioning independent
lerna info ci enabled
lerna notice filter including "@openameba/spindle-tokens"
lerna info filter [ '@openameba/spindle-tokens' ]
> @openameba/spindle-tokens:export
$ run-p export:*
$ tsx scripts/color.ts
$ tsx scripts/animation.ts
/bin/sh: 1: tsx: not found
/bin/sh: 1: tsx: not found
error Command failed with exit code 1[27](https://github.com/openameba/spindle/actions/runs/15013285054/job/42185794204#step:6:28).
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this …
```
> chore: add tsx

- packages/spindle-ui/src/Modal/SemiModal.css
SemiModalのmax-heightについて
モバイル端末やタブレット端末でブラウザのNavigation barの高さが考慮されていないため、
考慮する形に修正しました。
before
after
| pc chrome | iOS(sheet) | iOS(popup) |
| --- | --- | --- |
| ![image](https://github.com/user-attachments/assets/880da7a5-dd13-4a95-811a-e26512633baf) | ![image](https://github.com/user-attachments/assets/b7664061-e09c-4ec6-988c-d203be00b0dc) | ![image](https://github.com/user-attachments/assets/ace09522-c61e-420a-8882-2c029c94717d) |
> fix(spindle-ui): fix semi modal style

- packages/spindle-ui/.bundlewatch.config.js
- packages/spindle-ui/src/InlineNotification/InlineNotification.stories.tsx
- packages/spindle-ui/src/InlineNotification/InlineNotification.tsx
InlineNotificationはchildrenとして `ReactElement` を期待する実装になっていましたが、この状態だとexampleにあるような
```tsx
<InlineNotification.Frame variant='information' visible>
<InlineNotification.Icon><Information aria-hidden="true"/></InlineNotification.Icon>
<InlineNotification.Text>ブログの管理者が承認するまで、コメントが反映されない場合があります</InlineNotification.Text>
<InlineNotification.TextButton>とじる</InlineNotification.TextButton>
</InlineNotification.Frame>
```
という使い方が出来ないため
```tsx
<InlineNotification.Frame variant='information' visible>
<>
<InlineNotification.Icon><Information aria-hidden="true"/></InlineNotification.Icon>
<InlineNotification.Text>ブログの管理者が承認するまで、コメントが反映されない場合があります</InlineNotification.Text>
<InlineNotification.TextButton>とじる</InlineNotification.TextButton>
</>
</InlineNotification.Frame>
```
このようにFragmentを利用して扱っていました。 …
> fix(spindle-ui): inlineNotificationがFragmentを受け取った際に値のコピーが上手く行かない問題を修正

- .npmrc
- .renovaterc.json
- .yarnrc
- モジュールを追加するとき常にバージョンを固定するのをやめました
- モジュールによってバージョンを固定するかどうかの設定を変えました
- ルートのpackage.jsonはバージョンを固定します
- packages配下のpackage.jsonはライブラリとして使用されるのでdevDependencies以外はバージョンを固定しません
> chore: update renovate settings

- packages/spindle-ui/.bundlewatch.config.js
- packages/spindle-ui/package.json
- packages/spindle-ui/src/Button/Button.css
- yarn.lock
Buttonコンポーネントのhoverとactive色がプリミティブカラーを使っていたのでテーマカラーに差し替えました。
元々トークン自体は用意されていたみたいなのですが利用されていなかったっぽいです。
色自体の変更はないのでユーザー影響はないです。
例えば `--color-active-contained-button` に差し替えましたが `--color-active-contained-button` が参照しているのは `--primary-green-100` って感じです。
> feat(spindle-ui): Buttonコンポーネントのhoverとactive色を差し替え

- packages/spindle-ui/src/Table/Table.css
- packages/spindle-ui/src/Table/Table.mdx
- packages/spindle-ui/src/Table/Table.stories.tsx
- packages/spindle-ui/src/Table/Table.test.tsx
- packages/spindle-ui/src/Table/Table.tsx
- packages/spindle-ui/src/Table/design-doc.md
- packages/spindle-ui/src/Table/index.ts
- packages/spindle-ui/src/index.css
Spindleに `Table` コンポーネントを追加します。
DesignDocのPRは #1324 です。
- 親コンポーネントの命名を `<Table>` -> `<Table.Frame>` に変更
- 他のコンポーネントの命名に揃える
- CSS Variablesの値を修正
- デザイナーと議論した上での修正
- Footer周りのCSS Variablesを刷新。headerと同じような設計に。
> feat(spindle-ui): add table component 

- packages/spindle-ui/package.json
- packages/spindle-ui/src/Dialog/Dialog.tsx
- packages/spindle-ui/src/Form/DropDown.tsx
- packages/spindle-ui/src/Form/InlineDropDown.tsx
- packages/spindle-ui/src/Modal/AppealModal.tsx
- packages/spindle-ui/src/Modal/SemiModal.tsx
- yarn.lock
ViteでSSRを実行した際に以下のようなエラーが出ていました。
```
TypeError: __vite_ssr_import_1__.default is not a function
at SemiModal (/path_to/node_modules/@openameba/spindle-ui/Modal
/SemiModal.mjs:64:36)
```
原因としては、react-merge-refsがCommonJS モジュールで、default exportを持たない形式で配布されているためだと考えられたため、ESM対応の別の手段に置き換えました。
use-callback-refから提供されるuseMergeRefsを利用するようにしました。
必要十分な機能をシンプルな実装で提供されているので、自前で実装することも少し考えたものの、メンテコストと天秤にかけて依存を追加する選択を取ってます。
(こちらは僕の方で実施済みなんですが、気になる方は試しても良いと思います。)
- viteでSSRできるパッケージを用意
- SemiModal等を読み込み問題のエラーが発生するかを確認
- spindleでこのブランチをチェックアウトし、spindle-uiでbuildを実行
- dist内の成果物を用意したパッケージのnode_modules内に上書き
- 再度確認してエラーが消えていることを確認
> feat(spindle-ui): react-merge-refsをuse-callback-refに置き換え

- packages/spindle-ui/src/Button/Button.figma.tsx
- packages/spindle-ui/src/Dialog/Dialog.figma.tsx
- packages/spindle-ui/src/Form/Checkbox.figma.tsx
- packages/spindle-ui/src/Form/Radio.figma.tsx
- packages/spindle-ui/src/Form/ToggleSwitch.figma.tsx
- packages/spindle-ui/src/IconButton/IconButton.figma.tsx
- packages/spindle-ui/src/InlineNotification/InlineNotification.figma.tsx
- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.figma.tsx
- packages/spindle-ui/src/NavigationTab/UnderlineTab/UnderlineTab.mdx
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.figma.tsx
- packages/spindle-ui/src/SnackBar/SnackBar.figma.tsx
Figma Dev Mode MCP Server経由でコードに起こすときにCSSのimportも含まれるようにCode Connectの設定を更新しました。
これでSpindle MCP Serverを使わなくてもCSSのimport文が含まれる予定です。
> chore(spindle-ui): add css import in figma code connect

- .github/workflows/release.yml
- packages/spindle-hooks/package.json
- packages/spindle-icons/package.json
- packages/spindle-syntax-themes/package.json
- packages/spindle-theme-switch/package.json
- packages/spindle-tokens/package.json
- packages/spindle-ui/package.json
[textlint-rule-preset-ameba](https://github.com/openameba/textlint-rule-preset-ameba/pull/97)でうまくいったので、こちらでもOIDC対応します。
- npm Trusted Publishing (OIDC) を採用し、パーソナルアクセストークンからOpenID Connectに移行
- PR作成で`PERSONAL_ACCESS_TOKEN`から`github.token`に切り替え (GitHub Actionsが自動で動かないかもですが、token消したいモチベーションの方が強いです)
- 不要な`pull-requests: write`権限を削除
- 非推奨の`::set-output`から`GITHUB_OUTPUT`環境変数に移行
- リポジトリURLのHTTPS形式化により、npm provenanceの正確な検証を実現
- すべてのpackage.jsonのリポジトリURLを`git+https`形式から`https`形式に更新
- モノレポ構造のためにディレクトリプロパティを各パッケージに追加
ref: https://docs.npmjs.com/trusted-publishers
---
This pull request updates the release workflow and improves package metadata for all sub-packages. The most significant changes ensure compatibility with npm's OIDC Trusted Publishing and enhance the accuracy of repository information in …
> ci: adopt npm Trusted Publishing (OIDC)

- .github/workflows/build-icon-from-figma.yml
- .github/workflows/build-icon.yml
- .github/workflows/build-tokens.yml
- .github/workflows/build.yml
- .github/workflows/deploy-highlightjs-styles-preview.yml
- .github/workflows/deploy-highlightjs-styles.yml
- .github/workflows/deploy-hooks-catalog.yml
- .github/workflows/deploy-hoooks-preview.yml
- .github/workflows/deploy-theme-switch-preview.yml
- .github/workflows/deploy-theme-switch.yml
- .github/workflows/deploy-ui-catalog.yml
- .github/workflows/deploy-ui-preview.yml
- .github/workflows/figma-code-connect.yml
- .github/workflows/lint-commit-message.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/visual-regression-test.yml
- package.json
- Add engines field to package.json specifying Node.js >=22
- Update all 17 GitHub Actions workflows to use node-version-file: package.json
- Centralize Node.js version management in package.json for easier maintenance
> ci: update Node.js version to 22 in GitHub Actions workflows

- .github/workflows/release.yml
[lernaで未対応](https://github.com/openameba/spindle/pull/1361#issuecomment-3305308333)のため一時的にnpm publishだけスクリプトで実行します。
---
- Replace lerna publish with lerna publish --skip-npm for tag/release creation
- Add individual npm publish with OIDC authentication for changed packages
- Add change detection step to skip release when no packages changed
- Use lerna changed command to get list of modified packages
- Remove --provenance flag as it's automatically enabled with OIDC
> ci: resolve E404 error in release workflow with OIDC authentication

- .github/workflows/release.yml
おかげ様で、OIDCのnpm publish完了しました！が、Pull Requestが作られなかったので修正しました。
:kan: 
---
- Add pull-requests: write permission to fix 'Resource not accessible by integration' error
- Add condition to create PR only when packages are changed
> ci: add pull-requests permission to release workflow

- packages/spindle-ui/.stylelintrc.json
- packages/spindle-ui/package.json
- packages/spindle-ui/src/Button/Button.css
- packages/spindle-ui/src/Dialog/Dialog.css
- packages/spindle-ui/src/DropdownMenu/DropdownMenu.css
- packages/spindle-ui/src/Form/Checkbox.css
- packages/spindle-ui/src/Form/DropDown.css
- packages/spindle-ui/src/Form/InlineDropDown.css
- packages/spindle-ui/src/Form/Radio.css
- packages/spindle-ui/src/Form/ToggleSwitch.css
- packages/spindle-ui/src/IconButton/IconButton.css
- packages/spindle-ui/src/InlineNotification/InlineNotification.css
- packages/spindle-ui/src/LinkButton/LinkButton.css
- packages/spindle-ui/src/Modal/AppealModal.css
- packages/spindle-ui/src/Modal/SemiModal.css
- packages/spindle-ui/src/SegmentedControl/SegmentedControl.css
- packages/spindle-ui/src/SnackBar/SnackBar.css
- packages/spindle-ui/src/TextButton/TextButton.css
- packages/spindle-ui/src/TextLink/TextLink.css
- packages/spindle-ui/src/Toast/Toast.css
思いの外変更多くなってしもた (まる)
focus時のアウトラインが表示されている
(前) https://ameba-spindle.web.app/?path=/story/form-checkbox--checkbox
(今) https://ameba-spindle--pr1367-chore-deps-stylelint-62s8imgf.web.app/?path=/story/form-checkbox--checkbox
動作に変更がない
(前) https://ameba-spindle.web.app/?path=/story/form-dropdown--drop-down
(今) https://ameba-spindle--pr1367-chore-deps-stylelint-62s8imgf.web.app/?path=/story/form-dropdown--drop-down
動作に変更がない
(前) https://ameba-spindle.web.app/?path=/story/form-inlinedropdown--medium
(今) https://ameba-spindle--pr1367-chore-deps-stylelint-62s8imgf.web.app/?path=/story/form-inlinedropdown--medium
focus時のアウトラインが表示されている
(前) https://ameba-spindle.web.app/?path=/story/form-radio--radio
(今) https://ameba-spindle--pr1367-chore-deps-stylelint-62s8imgf.web.app/?path=/story/form-radio--radio …
> chore: update stylelint to v16.24.0

- AGENTS.md
- CLAUDE.md
直近困った点のみを追加しました。他の観点やより良い方法があれば教えてください〜。
最小限気味で入れてますが、今後フローの変更により変わる可能性が高めです。
---
- Add commit convention guidelines following Conventional Commits 1.0.0
- Specify package name in scope for multiple packages without spaces
- Add code quality guidelines focusing on self-documenting code
- Emphasize comments on 'why' rather than 'what' or 'how'
- Prohibit agent-specific information in commits
> docs: add initial Spindle Agents Guide

- packages/spindle-ui/src/Modal/AppealModal.css
- packages/spindle-ui/src/Modal/AppealModal.tsx
- packages/spindle-ui/src/Modal/SemiModal.css
- packages/spindle-ui/src/Modal/SemiModal.tsx
[Dialogと同様](https://github.com/openameba/spindle/pull/1360)にModal系コンポーネントも開閉トランジッションを変更しました。
Storybookをポチポチして確認いただければと思います。
---
This pull request refactors the modal animation and transition logic for both `AppealModal` and `SemiModal` components to use modern CSS transitions instead of JavaScript-driven animation state and keyframes. The changes simplify the React component logic, improve accessibility, and provide smoother open/close transitions using CSS features like `@starting-style` and `:has()`. Legacy polyfill and animation code is removed, and the CSS is updated to use transitions for opacity and transforms.
**Modal Animation and Transition Refactor:**
* Replaced JavaScript-based animation state and keyframe-driven open/close logic in `AppealModal.tsx` and `SemiModal.tsx` with …
> feat(spindle-ui): migrate SemiModal, AppealModal to allow-discrete transitions

- package.json
- yarn.lock
zodのバージョンを上げたのですが、[まだ未対応](https://github.com/modelcontextprotocol/typescript-sdk/issues/555)かつ[型定義のコンフリクトを起こしてしまった](https://github.com/openameba/spindle/actions/runs/17909361250/job/50917076532)ので、対応されるまで固定して運用します。
---
確認方法
```
yarn
cd packages/spindle-mcp-server
yarn build
```
> chore(spindle-mcp-server): resolve Zod version conflict

- packages/spindle-mcp-server/src/server.ts
- packages/spindle-mcp-server/tsconfig.json
esmでビルドできておらず実行できなかったので修正しました。
確認方法
```
yarn
cd packages/spindle-mcp-server
yarn build
node dist/index.js
```
> fix(spindle-mcp-server): migrate to ES module format and update TypeScript config

- .github/workflows/release.yml
- CONTRIBUTING.md
パッケージごとのリリースも増えてきそうなのでリリースフローを `workflow_dispatch` にして選択できるようにしました。わかりにくいことがあればレビューコメントお願いします！
---
This pull request updates the release workflow to use a manual (workflow_dispatch) trigger with input options and improves the release process for multi-package repositories. It also updates the contributor documentation to match the new workflow and adds stricter checks for major releases to prevent accidental version bumps of unintended packages.
**Release workflow improvements:**
* Changed `.github/workflows/release.yml` to use `workflow_dispatch` so releases are triggered manually with selectable inputs for version type and package name, rather than automatically on branch pushes.
* Added logic to check that only the selected package has changes when performing a major release, …
> ci: update release workflow to use workflow_dispatch with package selection
